/* =================================================================
   data_cikmis_2024.js – Çıkmış Sorular 2024 Juni (THK1 + THK2)
   opts[0] = altijd het JUISTE antwoord. quiz.js shuffelt bij weergave.
   ================================================================= */
(function(){
var sets = {

// ═══ PEDO 2024 JUNI (10 vragen) ═══
pedo_cikmis_2024juni:{title:'Kindertandheelkunde Cikmis – 2024 Juni',questions:[
  {q:'Welke bewering over pijn bij kinderen is juist?',opts:['Pijn is persoonlijk en verschilt per kind afhankelijk van leeftijd en ontwikkeling','Pijn is bij elk kind gelijk en objectief meetbaar'],exp:'Pijn is subjectief en wordt beinvloed door leeftijd, cognitieve ontwikkeling en eerdere ervaringen.'},
  {q:'Controle vanaf de eerste doorgebroken tand leidt tot ...',opts:['Een betere mondgezondheid bij kinderen','Geen opmerkelijk verschil vergeleken met controle vanaf 4 jaar'],exp:'Vroege controle (vanaf eerste tand) leidt aantoonbaar tot betere mondgezondheid bij kinderen.'},
  {q:'Als ouders tandartsangst hebben, dan ...',opts:['Kan het kind onbedoeld tandartsangst ontwikkelen','Heeft het kind altijd slechte mondgezondheid omdat ouders niet naar de tandarts gaan'],exp:'Angst van ouders kan onbewust worden overgedragen op het kind (modellering).'},
  {q:'SDF (zilveraminefluoride) wordt als goede beschermende methode beschouwd als het gebruikt wordt met welke frequentie?',opts:['2 keer per jaar','5 keer per jaar'],exp:'SDF 38% applicatie 2x per jaar is effectief voor remineralisatie en cariesstop bij kinderen.'},
  {q:'Als ouders niet willen meewerken aan het poetsen en het kind heeft kleine approximale caries, wat doet u?',opts:['Hall-kroon is een optie','Er is geen andere optie dan verwijzing naar een pedodontoloog'],exp:'Hall-kroon (preformed metal crown zonder preparatie) is bewezen effectief bij approximale caries in melkmolaren zonder medewerking voor poetsen.'},
  {q:'Shaping bij gedragsmanagement houdt in: behandeling verdelen in kleine stapjes. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Shaping = grote behandeling stapsgewijs opbouwen zodat het kind went aan de situatie.'},
  {q:'Conditionering bij gedragsmanagement houdt in: het aanleren van een bepaald gedrag. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Conditionering = operante conditionering waarbij gewenst gedrag wordt aangeleerd via beloning of herhaling.'},
  {q:'Een 7-jarig kind heeft voldoende motorische ontwikkeling om zelfstandig te poetsen, maar de ouders blijven verantwoordelijk. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Kinderen tot ca. 10 jaar hebben nog onvoldoende fijne motoriek; ouderlijk toezicht en bijpoetsen blijft noodzakelijk.'},
  {q:'ICDAS 3 beschrijft ...',opts:['Lokale kleine microcaviteit in het glazuur zonder dentine-betrokkenheid','Schaduwtekening in het dentine zonder caviteit'],exp:'ICDAS 3 = eerste tekenen van cavitatie: kleine microcaviteit lokaal in glazuur.'},
  {q:'Een angststoornis bij kinderen kenmerkt zich door ...',opts:['Excessieve angst voor een bepaalde situatie die de persoon probeert te vermijden','Realistische angst voor een bekende situatie zonder sociaal disfunctioneren'],exp:'Angststoornis = excessieve, irrationele angst die leidt tot vermijdingsgedrag en sociaal disfunctioneren.'},
]},

// ═══ CARIO 2024 JUNI (14 vragen) ═══
cario_cikmis_2024juni:{title:'Cariologie Cikmis – 2024 Juni',questions:[
  {q:'Een foto toont slijtage van een molaar met een bruine knobbel. Welke diagnose past het best?',opts:['Erosie','Abrasie'],exp:'Erosie: chemisch verlies zonder mechanisch contact, geeft bredere slijtage en bruine discoloratie van geexponeerd dentine.'},
  {q:'Een foto toont een kaasmolaar. Welke aandoening is het meest waarschijnlijk?',opts:['Hypomineralisatie (MIH)','Hypoplasie'],exp:'Kaasmolaar = Molaar-Incisief Hypomineralisatie (MIH): opaciteiten, uitbreken van glazuur. Hypoplasie = structuurgebrek in glazuurdikte.'},
  {q:'Een molaar heeft een cariesschaduw met weefselverlies. De caries is ...',opts:['Actief','Inactief'],exp:'Actieve caries: zacht, vochtig, met plaque geassocieerd, voortschrijdend weefselverlies. Inactief: hard, bruin, gepolijst oppervlak.'},
  {q:'Welke bewering over composiet applicatie in laagjes is juist?',opts:['Composietlaagjes mogen niet meer dan 2 mm dik worden aangebracht','Composietlaagjes kunnen gewoon meer dan 2 mm dik worden aangebracht'],exp:'Maximale laagdikte composiet is 2 mm vanwege beperkte lichtpenetratie voor adequate polymerisatie.'},
  {q:'Welk hechtingssysteem geeft de beste hechting aan glazuur?',opts:['3-staps spoel-en-ets systeem (total-etch)','Sterk 2-staps self-etch systeem'],exp:'3-staps total-etch: aparte etsing met fosforzuur geeft maximale glazuurbinding. Self-etch mist dit sterke etsprofiel.'},
  {q:'Wat is de definitie van secundaire actieve caries?',opts:['Caries met plaque en groeiende laesie rondom een bestaande restauratie','Caries die ontstaat zonder aantoonbare plaque'],exp:'Secundaire actieve caries = recurrente caries rondom restauratie met aanwezige plaque en progressief weefselverlies.'},
  {q:'Welk tandweefsel zou nadeliger worden beinvloed door te lang etsen?',opts:['Dentine','Glazuur'],exp:'Overetsen van dentine beschadigt collageen netwerkstructuur waardoor hybride laag verslechtert. Glazuur is minder gevoelig.'},
  {q:'Aan welk tandweefsel kan GIS (glasionomeercement) chemisch hechten?',opts:['Zowel dentine als glazuur','Alleen glazuur'],exp:'GIS hecht chemisch aan calciumionen in zowel glazuur als dentine via polyzuurgroepen. Geen etsen noodzakelijk.'},
  {q:'GIS heeft dagen nodig om volledig uit te harden. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'GIS rijpt 24-48 uur; de eerste 24 uur is het materiaal gevoelig voor uitdroging en vochtopname. Volledige rijping kan weken duren.'},
  {q:'Extrand score 4 bereikt tot welk weefsel?',opts:['Tot de pulpa','Tot het dentine'],exp:'Extrand score 4 = caviteit tot in de pulpa (of bijna pulpa). Score 3 = dentine.'},
  {q:'Bij een Extrand score verandering van 1 naar 2, wat doet u?',opts:['Preventie met fluorlak aanbrengen','Sealants plaatsen om remineralisatie mogelijk te maken'],exp:'Extrand 1 naar 2 = vroege glazurcaries zonder caviteit; fluorlak stimuleert remineralisatie. Sealants bij Extrand 0 preventief.'},
  {q:'Wanneer bepaalt u de kleur van het composiet?',opts:['Na verwijdering van aanslag en voor verwijdering van caries','Na cariesverwijdering en rubberdam plaatsen'],exp:'Kleur bepalen voor isolatie en dehydratatie van tand; een uitgedroogde tand lijkt lichter dan de werkelijke kleur.'},
  {q:'Een stift is niet geindicieerd voor een wortelkanaalbehandeld element als er voldoende weefsel aanwezig is. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Een stift vergroot de wortelsterkte niet; bij voldoende coronaal weefsel is directe opbouw zonder stift de voorkeur.'},
  {q:'Welke aandoening toont bij foto glazuurafwijkingen op elementen 12-11-21-22?',opts:['Fluorose','Hypomineralisatie'],exp:'Fluorose: symmetrisch wit-bruin gespikkeld patroon op meerdere elementen door overmatige fluoride-inname tijdens tandvorming.'},
]},

// ═══ PARO 2024 JUNI (15 vragen) ═══
paro_cikmis_2024juni:{title:'Parodontologie Cikmis – 2024 Juni',questions:[
  {q:'Bij patienten met een plaquescore van minder dan 20% hoeft tijdens de initiele behandeling geen mondhygiene-instructie te worden gegeven. Juist of onjuist?',opts:['Onjuist','Juist'],exp:'Mondhygieneinstructie is altijd onderdeel van de initiele paro-behandeling, ongeacht de plaquescore.'},
  {q:'Diabetes is bijna nooit gerelateerd aan parodontitis. Juist of onjuist?',opts:['Onjuist','Juist'],exp:'Er is een bidirectionele relatie: diabetes verhoogt het risico op parodontitis en parodontitis bemoeilijkt glykemische regulatie.'},
  {q:'Parodontitis komt voor in ongeveer welk percentage van de bevolking boven de 50 jaar?',opts:['50%','25%'],exp:'Ernstige parodontitis treft circa 50% van de bevolking boven de 50 jaar wereldwijd (WHO-data).'},
  {q:'PPS-screening dient te starten vanaf 18 jaar. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Volwassen patienten (18+) worden gescreend met de DPSI/PPS. Bij jongeren kan eerder gestart worden bij risicofactoren.'},
  {q:'Roken vermindert bij paro-patienten ...',opts:['Bloeding na sonderen (BOP)','Tandplak en bloeding tegelijkertijd'],exp:'Nicotine veroorzaakt vasoconstrictie en vermindert gingivale doorbloeding, waardoor BOP onderdrukt wordt ook bij actieve parodontitis.'},
  {q:'CHX (chloorhexidine) is antibacterieel. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'CHX is een breed antibacterieel middel met substantiviteit (hechting aan mondslijmvlies tot 12 uur).'},
  {q:'Een pocket meet je tussen ...',opts:['Gingivarand en sulcusbodem','Gingivarand en botniveau'],exp:'Pocketdiepte = afstand van gingivarand tot sulcusbodem. Botniveau wordt bepaald op rontgenfoto.'},
  {q:'Een pocket van 10 mm wordt na paro-behandeling gereduceerd tot 6 mm bij element 12. Is dit resultaat voldoende?',opts:['Onvoldoende, want pocket is niet kleiner dan 5 mm','Voldoende, want er is 4 mm reductie bereikt'],exp:'Behandeldoel is pocket kleiner dan of gelijk aan 5 mm. Bij 6 mm restpocket is het resultaat onvoldoende.'},
  {q:'Waarbij geeft paro-behandeling een beter resultaat (meer aanhechtingswinst): 6 mm pocket mp 26 of 10 mm pocket mb 13?',opts:['10 mm pocket mb 13','6 mm pocket mp 26'],exp:'Grotere initiole pocketdiepte (10 mm) geeft na SRP meer absolute aanhechtingswinst dan een kleiner pocket.'},
  {q:'Welk element heeft bijna nooit een anatomische variant (groef) aan de wortel?',opts:['45 (onderste tweede premolaar)','24 (bovenste eerste premolaar)'],exp:'Bovenste premolaren (24/25) hebben frequent palatinale groeven. Onderpremolaar 45 heeft zelden wortelvarianten.'},
  {q:'Een 16-jarige patient heeft pijnlijke gingiva, vieze smaak, losse tanden en necrotische papillen. Diagnose?',opts:['NUP (Necrotiserende Ulceratieve Parodontitis)','NUG (Necrotiserende Ulceratieve Gingivitis)'],exp:'NUP = NUG + botverlies en tandloslating. Losse tanden en leeftijd 16 jaar met botverlies wijzen op NUP.'},
  {q:'Bij welke PPS-score is er een pocket van x mm waarbij de score 3 van toepassing is?',opts:['Pocket 3,5-5,5 mm (kleurband gedeeltelijk zichtbaar)','Pocket dieper dan 5,5 mm (kleurband verdwenen)'],exp:'PPS/DPSI 3: kleurband gedeeltelijk in pocket, pocketdiepte 3,5-5,5 mm.'},
  {q:'Wanneer geef je antibiotica bij paro-behandeling?',opts:['Gelijktijdig met of direct na de laatste SRP-sessie','Voor de paro-behandeling start'],exp:'Timing antibiotica: bij of direct na subgingivale SRP, zodat bacterieen blootstaan aan het middel na disruptie van biofilm.'},
  {q:'Een patient komt voor het eerst. Bij welke situatie geef je antibiotica?',opts:['Onvoldoende resultaat na eerdere behandeling bij goede mondhygiene of roken','Altijd bij eerste bezoek bij paro-patienten'],exp:'AB is niet standaard bij eerste bezoek; indicatie bestaat bij persisterende paro na adequate SRP met goede MH of risicofactoren.'},
  {q:'Wat is de meest voorkomende reden voor tandverlies na tunneloperatie bij graad-3-furcatie defect?',opts:['Caries','Fractuur'],exp:'Na tunneloperatie is de furcatie toegankelijk maar ook gevoelig voor caries; dit is de voornaamste oorzaak van tandverlies.'},
]},

// ═══ ENDO 2024 JUNI deel 1 (15 vragen) ═══
endo_cikmis_2024juni_a:{title:'Endodontologie Cikmis – 2024 Juni (deel 1)',questions:[
  {q:'Welke vorm heeft de endodontische toegangsopening van een bovenste incisief?',opts:['Driehoekig','Trapezoid'],exp:'Bovenincisief: driehoekige toegangsopening met basis palatinaal. Bovenmolaren: driehoekig. Kies: ruitvormig.'},
  {q:'Na een wortelkanaalbehandeling van een bovenmolaar met MOD-vulling: welke restauratie is het beste?',opts:['Knobbelbedekking (kroon)','Alleen de oude vulling vervangen met composiet'],exp:'WKB + MOD-preparatie verzwakt de tand sterk; knobbelbedekking is noodzakelijk om tandbreuk te voorkomen.'},
  {q:'Welke bewering over natriumhypochloriet (NaOCl) is juist?',opts:['Het effect is kortdurend en het lost organisch weefsel op','NaOCl hecht chemisch aan worteldentine'],exp:'NaOCl werkt direct maar het effect is kortdurend (geen substantiviteit). Het lost organisch weefsel (pulpa) enzymatisch op.'},
  {q:'Waarom is een K-flexo vijl flexibeler dan een klassieke stainless steel vijl?',opts:['De doorsnede (profiel) van de vijl is anders gevormd','Het materiaal is nikkel-titanium'],exp:'K-flexo vijl: stainless steel maar met driehoekige doorsnede in plaats van vierkant, waardoor meer flexibiliteit.'},
  {q:'Welke bewering over stiften is juist?',opts:['Als voldoende dentine aanwezig is, hoef je geen stift te gebruiken voor opbouw','Stiften zijn altijd nodig voor esthetiek na WKB'],exp:'Een stift vergroot de retentie van de opbouw maar versterkt de wortel niet; bij voldoende coronaal dentine is een stift niet nodig.'},
  {q:'Een 8-jarig kind presenteert zich 3 dagen na een gecompliceerde kroonfractuur. Welke behandeling?',opts:['Partiele pulpotomie','Volledige pulpectomie'],exp:'3 dagen na gecompliceerde fractuur bij kind 8 jaar (open apex): partiele pulpotomie (Cvek) houdt vitaliteit en wortelgroei in stand.'},
  {q:'Een avulsie heeft plaatsgevonden maar terugplaatsen was niet mogelijk. Welk bewaarmedium is het beste?',opts:['In een glas melk','In de omslagplooi van de patient'],exp:'Melk is isotoon en bevat groeifactoren; houdt PDL-cellen het langst levend. Omslagplooi is tweede keuze bij kinderen.'},
  {q:'Welke bewering over GIC als wortelkanaalcement is juist?',opts:['GIC wortelkanaalcement is moeilijk te verwijderen indien herbehandeling nodig is','GIC hecht niet aan worteldentine'],exp:'GIC cement hecht chemisch aan dentine en is daardoor zeer lastig te verwijderen bij herbehandeling; dit is een nadeel.'},
  {q:'Bij GIC als wortelkanaalcement is de uithardingstijd vertraagd. Welk voordeel heeft dit?',opts:['Minder krimp tijdens uitharden','Wortelkanaalvulling duurt langer'],exp:'Langzamere polymerisatie geeft minder krimp en daarmee een betere marginale aansluiting van het cement.'},
  {q:'Voor goede irrigatie bij een vijldiameter van 30 is een taper van hoeveel procent nodig?',opts:['6%','2%'],exp:'Een taper van minimaal 6% bij diameter 30 garandeert dat de irrigatievloeistof de apex bereikt door adequate kanaalontsluiting.'},
  {q:'Bij avulsie van een volgroeide tand (gesloten apex): wanneer start je de WKB?',opts:['7-14 dagen na replantatie','Vitaliteit afwachten'],exp:'Gesloten apex: revascularisatie is onmogelijk. WKB starten 7-14 dagen na replantatie, voor verwijdering van de spalk.'},
  {q:'C-vormige kanaalconfiguratie komt het meest voor bij ...',opts:['Ondermolaren','Bovenmolaren'],exp:'C-vormige kanalen komen het meest voor bij onderste tweede molaren (ook wel bij bovenste derde molaren, maar ondermolaar is het klassiek).'},
  {q:'Welk element heeft de meeste kans op een tweede kanaal?',opts:['Ondercuspidaat','Bovencuspidaat'],exp:'Onderste cuspidaat (33/43) heeft in ca. 15-30% twee kanalen. Bovencuspidaat vrijwel altijd een kanaal.'},
  {q:'Waarom wordt coffeedam gebruikt bij WKB?',opts:['Om aseptisch te werken en contaminatie vanuit de mond te voorkomen','Om bacteriele infectie vanuit geinfecteerde kanalen naar de mondomgeving te voorkomen'],exp:'Coffeedam: primair doel is aseptische werkomgeving (voorkomen contaminatie vanuit speeksel naar kanaal).'},
  {q:'Welke bewering over gebroken vijlen is juist?',opts:['Eerst coronaal prepareren voor de apicale lengte bereikt wordt, heeft minder kans op vijlbreuk','Het behandelsucces is 20% lager bij een gebroken vijl'],exp:'Corono-apicale preparatievolgorde vermindert torsiebelasting; vijlbreuk treedt vaker op bij directe apicale preparatie.'},
]},

// ═══ ENDO 2024 JUNI deel 2 (5 vragen) ═══
endo_cikmis_2024juni_b:{title:'Endodontologie Cikmis – 2024 Juni (deel 2)',questions:[
  {q:'Hoe lang duurt de napijn na een wortelkanaalbehandeling gemiddeld?',opts:['3-5 dagen','Al gauw een week'],exp:'Postoperatieve pijn na WKB is normaal 3-5 dagen aanwezig. Langer dan een week is ongewoon en vraagt om evaluatie.'},
  {q:'Een echte apicale cyste ...',opts:['Kan alleen histologisch worden gediagnostiseerd (niet radiologisch)','Kan genezen na WKB omdat de cyste de wortel omgeeft'],exp:'Een echte apicale cyste heeft een volledig epitheliaal bekleed lumen zonder verbinding met de wortelcanaal; genest niet na WKB, vereist apicale resectie.'},
  {q:'Wat is een apicaal litteken (apical scar)?',opts:['Bindweefsel ter plaatse van eerdere apicale laesie','Osteodentine gevormd na genezing'],exp:'Apicaal litteken = fibrotisch bindweefsel na genezing van periapicale laesie; blijft zichtbaar op rontgen maar is klinisch inactief.'},
  {q:'Waarom houden we een tand vitaal bij jonge kinderen?',opts:['Om de wortelgroei intact te behouden (apexogenese)','Om de positie van de tand in de tandboog te bewaren'],exp:'Vitaliteitsbehoud bij open apex = apexogenese: de wortel groeit verder tot fysiologische lengte met gesloten apex.'},
  {q:'Glasvezel brengt de spanning beter over naar het dentine dan een metalen stift. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Glasvezel heeft een elasticiteitsmodulus vergelijkbaar met dentine, waardoor spanningsoverdracht homogener is en wortelbreuk minder voorkomt.'},
]},

// ═══ SPEEKSEL 2024 JUNI (8 vragen) ═══
speeksel_cikmis_2024juni:{title:'Speekselleer Cikmis – 2024 Juni',questions:[
  {q:'De pH is lager bij gestimuleerde speeksel vergeleken met rustspeeksel. Juist of onjuist?',opts:['Onjuist','Juist'],exp:'Gestimuleerde speeksel heeft een hogere pH (meer basisch) door toegenomen bicarbonaatproductie. Rustspeeksel heeft lagere pH.'},
  {q:'De parotis speekselproductie neemt toe in de volgorde: slapen < rust < kauwen. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Speekselproductie: nachts (slapen) het laagst, in rust intermediair, bij kauwen het hoogst. Parotis reageert sterk op mechanische stimulatie.'},
  {q:'De behandeling van intra-orale halitose is: tongschraper en indien nodig mondspoel. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Intra-orale halitose: oorzaak is VSC-productie door bacterieen op tong; tongschraper + antiseptische mondspoel is eerste lijn.'},
  {q:'Halitose kan door stress worden veroorzaakt. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Stress activeert het sympathische zenuwstelsel wat speekselproductie vermindert (droge mond), waardoor VSC-bacterieen meer kans krijgen.'},
  {q:'Waar komen de meeste speekselstenen (sialolithiasis) voor?',opts:['Glandula submandibularis','Glandula parotis'],exp:'Glandula submandibularis: slijmerig, alkalisch speeksel in een lange opstijgende ductus Wharton maakt het gevoelig voor steenvorming.'},
  {q:'Patienten die roken hebben een verminderde speekselproductie. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Chronisch roken beinvloedt speekselklier parenchym en vermindert de productiecapaciteit, met name van seromuceuze klieren.'},
  {q:'Xerostomie kan worden veroorzaakt door medicijngebruik. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Meer dan 400 medicijnen hebben droge mond als bijwerking, o.a. antidepressiva, antihistaminica en antihypertensiva.'},
  {q:'Hyposalivatie wordt gemeten bij zowel gestimuleerde als rustspeeksel. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Hyposalivatie diagnose vereist meting van rustflow (< 0,1 ml/min) EN gestimuleerde flow (< 0,7 ml/min) voor volledig beeld.'},
]},

// ═══ RADIOLOGIE 2024 JUNI (15 vragen) ═══
radio_cikmis_2024juni:{title:'Radiologie Cikmis – 2024 Juni',questions:[
  {q:'Contrast (grijsheid) op een rontgenfoto is afhankelijk van de dichtheid van het materiaal. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Dichter materiaal absorbeert meer rontgenstraling en verschijnt witter (radioopaak). Minder dicht = meer straling doorgelaten = donkerder.'},
  {q:'Op een OPG zijn geimpacteerde hoektanden zichtbaar. Hoe bepaal je of ze palatinaal of buccaal liggen?',opts:['Palatinale hoektanden liggen verder van de worteltoppen verwijderd en lijken groter op OPG (vergroting)','Buccale hoektanden liggen verder verwijderd van de film en lijken groter'],exp:'Buccaal object: verder van film = meer vergroot op OPG. Palatinaal: dichter bij film = minder vergroot, andere positie t.o.v. nabuurelementwortel.'},
  {q:'TMS-basis rontgencursus: hoe frequent is naschooling wettelijk verplicht?',opts:['4 uur per 5 jaar','Naschooling is niet verplicht'],exp:'BIG-wet en KNMT-richtlijn: TMS-basisopleiding vereist 4 uur naschooling per 5 jaar om bekwaamheid te behouden.'},
  {q:'Welke bewering is juist over tandartsassistenten en rontgenfotografie?',opts:['Een tandartsassistente met rontgendiploma kan geen rontgenfoto maken als zij zichzelf niet voldoende bekwaam acht','Een tandartsassistente zonder rontgendiploma kan fotos maken na begeleiding van een BIG-geregistreerde tandarts'],exp:'BIG-wet: ook met diploma geldt eigen verantwoordelijkheid voor bekwaamheid. Zonder diploma is zelfstandig rontgen niet toegestaan.'},
  {q:'Op een OPG is een groot radiolucent gebied zichtbaar rondom element 48. Meest waarschijnlijke diagnose?',opts:['Folliculaire cyste','Ameloblastoom'],exp:'Folliculaire cyste is de meest voorkomende oorzaak van grote radiolucente laesie rondom geimpacteerde verstandskies. Ameloblastoom is zeldzamer.'},
  {q:'Het risico op tumorinductie door rontgenstraling ...',opts:['Is groter bij jonge mensen','Is groter bij oudere mensen'],exp:'Jonge cellen met hoge delingactiviteit zijn stralingsgevoeliger. Kinderen hebben hogere tumorinductierisico per dosis.'},
  {q:'Het parodontale ligament (PDL) is op een rontgenfoto radiolucent. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'PDL bestaat uit zacht weefsel (collageen vezels) en is radiolucent (donkere lijn). Lamina dura (compact bot) eromheen is radioopaque.'},
  {q:'Een bitewing is geindiceerd voor beoordeling van caries, parodontitis en approximale restauraties. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Bitewing toont approximale caries, interdentaal botniveau (vroege paro) en kwaliteit van approximale restauraties optimaal.'},
  {q:'Welk percentage van rontgenfotokopieren is toegankelijk volgens de KNMT-richtlijn?',opts:['20%','10%'],exp:'KNMT-richtlijn: patienten hebben recht op kopie van rontgenfoto; administratiekosten mogen in rekening worden gebracht, geen percentage beperking op toegankelijkheid.'},
  {q:'Een halsschaduw op een rontgenfoto wordt voornamelijk veroorzaakt door ...',opts:['De contour van het element op het niveau van de glazuurcementgrens','De tongpositie tijdens de opname'],exp:'Halsschaduw (cervicale burnout): radiolucente zone door de dunste doorsnedevan de tand ter hoogte van de glazuurcementgrens.'},
  {q:'Welke bewering over lamina dura bij pulpitis is juist?',opts:['Er is geen resorptie van lamina dura bij pulpitis (alleen bij periapicale ontsteking)','Er is resorptie van lamina dura bij chronische maar niet bij acute pulpitis'],exp:'Lamina dura resorbeert alleen bij periapicale parodontitis (na pulpanecrose), niet bij pulpitis zolang het periapicale weefsel intact is.'},
  {q:'Bij het MAL-element (linguale positie): bij een distale rontgenfoto verschuift het beeld naar ...',opts:['Naar distaal','Naar mesiaal'],exp:'MAL-regel: Mesiale opname = verschuiving Aan Lingual naar mesiaal. Distale opname = palatinale/linguale element schuift naar distaal.'},
  {q:'Op een OPG zijn wervels zichtbaar en de tanden lijken te lachen (smiley-stand). Welke fout is gemaakt?',opts:['Hoofd te ver naar achteren (chin up)','Hoofd te ver naar voren (chin down)'],exp:'Hoofd naar achteren = negatieve Frankfort-hoek = smiley-stand tanden, wervels projecteren over mandibula.'},
  {q:'Risico op tumorinductie door tandheelkundige rontgenstraling vergeleken met achtergrondstraling is ...',opts:['Zeer klein en verwaarloosbaar bij goede techniek','Significant en moet altijd worden vermeden'],exp:'Tandheelkundige rontgendoses zijn extreem laag; individueel tumorrisico is verwaarloosbaar met juiste apparatuur en indicatiestelling.'},
  {q:'Op een OPG zijn speekselstenen in de mandibulaire glandula zichtbaar als ...',opts:['Radioopaque (witte) structuren in het verloop van de ductus','Radiolucente gebieden ter hoogte van de submandibulaire klier'],exp:'Speekselstenen bestaan uit calciumfosfaat en zijn radioopaque; zichtbaar als witte structuren in het verloop van ductus Wharton.'},
]},

// ═══ BASIS MEDISCH 2024 JUNI deel 1 (15 vragen) ═══
basis_cikmis_2024juni_a:{title:'Basis Medisch Cikmis – 2024 Juni (deel 1)',questions:[
  {q:'Welke aandoening is een absolute contraindicatie voor elektieve tandheelkundige behandeling?',opts:['Ongecontroleerde hyperparathyreodie','Gecontroleerde hypertensie'],exp:'Ongecontroleerde hyperparathyreodie: verhoogd PTH leidt tot botresorptie en verhoogd fractuurrisico; elektieve ingrepen zijn gecontraindiceerd.'},
  {q:'Een patient met hemofilie A: is het veilig om locale verdoving te geven?',opts:['Ja, infiltratie-verdoving is veilig; blokverdoving vereist voorzorg','Nee, geen verdoving geven bij hemofilie A'],exp:'Infiltratie (supraperiostaal) is veilig bij hemofilie A. Mandibulaire blokverdoving risico op bloeding in pterygomandibulaire ruimte; overleg hematologie.'},
  {q:'TIA 4 weken geleden: voer je de behandeling na 3 maanden uit?',opts:['Juist','Onjuist'],exp:'Na TIA: minimaal 3 maanden wachten voor elektieve ingrepen vanwege hoog risico op CVA in de eerste weken; na 3 maanden is risico gedaald.'},
  {q:'Een patient met de ziekte van Addison produceert onvoldoende cortisol. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Addison = primaire bijnierinsufficientie: onvoldoende cortisolproductie. Risico op adrenale crisis bij stress (tandheelkundige behandeling).'},
  {q:'Hoge vaccinatiegraad in een populatie leidt tot ...',opts:['Kudde-immuniteit (herd immunity)','Individuele immuniteit alleen'],exp:'Kudde-immuniteit: voldoende gevaccineerden beschermen ook niet-gevaccineerden door onderbreking van de transmissieketen.'},
  {q:'Graves-ziekte (hyperthyreodie) kenmerkt zich o.a. door ...',opts:['Gewichtsverlies ondanks normale of verhoogde eetlust','Gewichtstoename en vermoeidheid'],exp:'Graves: auto-immuun hyperthyreodie met verhoogde metabolisme, gewichtsverlies, tachycardie, tremor en exoftalmie.'},
  {q:'Kahler-ziekte (multipel myeloom) kan leiden tot ...',opts:['Kaakfractuur door botdestructie','Sinusitis maxillaris'],exp:'Multipel myeloom: plasmaceltumor met lytische botlaesies ook in de kaak. Pathologische fractuur is een bekende complicatie.'},
  {q:'COPD wordt het meest veroorzaakt door ...',opts:['Roken','Erfelijke aanleg'],exp:'COPD: > 90% van gevallen is gerelateerd aan (langdurig) roken. Roken veroorzaakt chronische bronchitis en emfyseem.'},
  {q:'Bij een verhoogde bloeddruk van 194/102 mmHg: voer je de tandheelkundige behandeling uit?',opts:['Nee, geen behandeling; doorverwijzen voor bloeddrukbehandeling','Ja, behandeling gaat door met extra voorzorgen'],exp:'Bloeddruk > 180/110 mmHg = grade 3 hypertensie: geen elektieve behandeling. Pijnbestrijding en doorverwijzing naar arts.'},
  {q:'Acetylsalicylzuur (Ascal) stoppen voor tandextractie?',opts:['Onjuist, Ascal niet stoppen','Juist, altijd stoppen voor extractie'],exp:'Ascal NIET stoppen: trombose-risico is groter dan bloedingsrisico bij tandextractie. Lokale hemostase volstaat.'},
  {q:'Hypoglykemie wordt acuut behandeld met ...',opts:['Dextro-tablet (glucose)','Insuline'],exp:'Hypoglykemie: direct 15-20 g snel opneembare glucose geven (dextrotablet, suikerthee). Insuline verlaagt glucose en is gecontra-indiceerd.'},
  {q:'Glazuurafwijkingen kunnen optreden bij coeliakie. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Coeliakie leidt via malabsorptie van calcium en vitamine D tot glazuurhypoplasie, met name in het permanente gebit.'},
  {q:'Multipele sclerose kan tremoren veroorzaken die tandheelkundige behandeling bemoeilijken. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'MS-symptomen zoals tremor, spasticiteit en vermoeidheid zijn relevant voor tandheelkundige behandelplanning en instrumentkeuze.'},
  {q:'Tandverkleuring kan optreden als bijwerking van welk antibioticum?',opts:['Tetracycline','Amoxicilline'],exp:'Tetracycline bindt aan calciumionen in tandweefsel tijdens mineralisatie en veroorzaakt grijsbruine intrinsieke verkleuring.'},
  {q:'Beta-blokkers verlagen de bloeddruk. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Beta-blokkers blokkeren beta-adrenerge receptoren: verminderd hartminuutvolume en renine-afgifte leiden tot bloeddrukdaling.'},
]},

// ═══ BASIS MEDISCH 2024 JUNI deel 2 (15 vragen) ═══
basis_cikmis_2024juni_b:{title:'Basis Medisch Cikmis – 2024 Juni (deel 2)',questions:[
  {q:'Astma-aanval kenmerkt zich door ...',opts:['Piepend ademhalen (wheeze) door bronchospasme','Rochelend ademhalen door vloeistof in de longen'],exp:'Astma: reversibele bronchoconstractie geeft expiratoire wheeze. Rochelend = hartfalen/pneumonie.'},
  {q:'HSV (herpes simplex virus) actieve uitbraak bij patient: behandeling zonder extra maatregelen? Juist of onjuist?',opts:['Onjuist','Juist'],exp:'Bij actieve HSV-uitbraak: geen electieve behandeling vanwege besmettelijkheid en risico op verspreiding. Handschoenen en masker volstaan niet altijd.'},
  {q:'Onvoldoende gereguleerde diabetes verhoogt het cariesrisico. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Slechte diabetesregulatie: verhoogd glucosegehalte in speeksel voedt cariogene bacterieen, verminderde speekselkwaliteit.'},
  {q:'Gastro-oesofageale reflux veroorzaakt erosie van het gebit voornamelijk op ...',opts:['Palatinale/linguale vlakken','Buccale vlakken'],exp:'Maagzuur bereikt de mondholte en erodeert bij voorkeur de palatinale vlakken van bovenelementen en linguale vlakken van onderelementen.'},
  {q:'Tanderosie wordt veroorzaakt door plaquebacterien. Juist of onjuist?',opts:['Onjuist','Juist'],exp:'Erosie is chemische aantasting door zuren (dietair of gastro-oesofageaal), niet door bacterieel metabolisme (dat is caries).'},
  {q:'Cytostatica verhogen het infectierisico. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Cytostatica (chemotherapie) veroorzaken beenmergdepressie met leukopenie, waardoor het immuunsysteem verzwakt en infectierisico toeneemt.'},
  {q:'Osteoporose wordt gekenmerkt door: osteoblasten actiever dan osteoclasten. Juist of onjuist?',opts:['Onjuist','Juist'],exp:'Osteoporose: disbalans waarbij osteoclasten MEER actief zijn dan osteoblasten, wat leidt tot netto botverlies en verhoogd fractuurrisico.'},
  {q:'HIV-patienten kunnen ernstige parodontitis ontwikkelen. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'HIV-gerelateerde paro: verminderde cellulaire immuniteit bevordert agressieve necrotiserende paro-vormen (NUG/NUP/NUS).'},
  {q:'Bisfosfonaten werken via ...',opts:['Remming van osteoclasten','Stimulatie van osteoblasten'],exp:'Bisfosfonaten inactiveren osteoclasten door binding aan botoppervlak; risico op osteonecrose van de kaak (MRONJ) bij hoge doses.'},
  {q:'Droge mond is een bijwerking van anticholinergica. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Anticholinergica blokkeren de muscarinereceptoren van speekselklieren, wat speekselsecretie sterk vermindert.'},
  {q:'Omeprazol is een ...',opts:['Protonpompremmer (PPI)','H2-receptorantagonist'],exp:'Omeprazol: irreversibele PPI, remt H+/K+-ATPase in maagwand. Gebruik bij GERD en peptisch ulcus. Relevant voor tandarts: minder maagzuur = minder erosie.'},
  {q:'Paracetamol heeft geen bloedstelpend effect. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Paracetamol remt COX centraal maar heeft geen klinisch relevant effect op trombocytenfunctie, anders dan NSAID.'},
  {q:'Hoge dosering corticosteroiden kan leiden tot ...',opts:['Adrenale suppressie en verhoogd infectierisico','Verhoogde botdichtheid'],exp:'Langdurige hoge dosis corticosteroiden: HPA-as suppressie, immunosuppressie, osteoporose en verhoogd infectierisico.'},
  {q:'Bij nierinsufficiency zijn NSAID gecontra-indiceerd. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'NSAID remmen prostaglandinesynthese in de nier, verminderen renale doorbloeding en kunnen acute nierinsufficiency verergeren.'},
  {q:'Biologische beschikbaarheid van een geneesmiddel verwijst naar ...',opts:['De fractie van het ingenomen middel die de systemische circulatie bereikt','De snelheid waarmee het middel wordt afgebroken'],exp:'Biologische beschikbaarheid (F): hoeveel % van de dosis onveranderd de systemische circulatie bereikt. Oraal < IV door first-pass effect.'},
]},

// ═══ KINESIO 2024 JUNI (10 vragen) ═══
kinesio_cikmis_2024juni:{title:'Kinesiologie/TMD Cikmis – 2024 Juni',questions:[
  {q:'Arthrogene pijn van het kaakgewricht heeft een brandend karakter. Juist of onjuist?',opts:['Onjuist','Juist'],exp:'Arthrogene pijn is scherp, drukkend of zeurend bij beweging. Brandende pijn is meer neurogeen of myogeen van karakter.'},
  {q:'Bij een Dahl-techniek van 6 mm verhoging: welk effect wordt verwacht op de occlusie?',opts:['Intrusive remodellering van de niet-contacterende elementen','Directe stabiele occlusie op alle elementen'],exp:'Dahl-principe: verhoging op anterieur segment leidt tot intrusie van die elementen en extrusie van posterieure elementen tot nieuw occlusaal evenwicht.'},
  {q:'In achteroverliggende positie schuift de mandibula vergeleken met rechtopzittende positie ...',opts:['Naar mesiaal (anterieur)','Naar distaal (posterieur)'],exp:'In rugligging trekt de zwaartekracht de mandibula naar voor (mesiaal); dit is relevant bij occlusaal onderzoek in liggende patient.'},
  {q:'Acuut open slot (open lock) van het kaakgewricht: wat doe je?',opts:['Meteen reponeren (manuele repositie)','Doorverwijzen naar kaakchirurg'],exp:'Acuut open lock = anterieure dislocatie van de condylus. Directe manuele repositie is de behandeling; uitstel verergert spierspasme.'},
  {q:'Symptomatische anterieure discusverplaatsing zonder reductie: doorsturen naar fysiotherapeut. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'ADD zonder reductie met beperkte mondopening: fysiotherapeutische mobilisatie en oefentherapie is de eerste lijn. Chirurgie zelden nodig.'},
  {q:'Een opbeetplaat tot de tweede molaren is correct. Juist of onjuist?',opts:['Onjuist','Juist'],exp:'Opbeetplaat dient contact te maken op ALLE posterieure elementen inclusief tweede molaren voor stabiele occlusale steun. Niet alleen tot eerste molaren.'},
  {q:'Bruxisme verergert slaapapneu. Juist of onjuist?',opts:['Onjuist','Juist'],exp:'Bruxisme en slaapapneu zijn comorbide maar causale relatie is niet aangetoond; bruxisme kan een arousalmechanisme zijn bij apneu-episodes.'},
  {q:'Bij anterieure discusverplaatsing MET reductie: het kaakgewrichtskopje ...',opts:['Schiet over de achterkant van de discus (klikkend geluid bij opening)','Blijft vastzetten achter de discus'],exp:'ADD met reductie: klik bij opening = condylus schuift onder de achterrand van de discus. Klik bij sluiting = condylus glijdt terug.'},
  {q:'Chronische TMD kan een progressief beloop hebben. Juist of onjuist?',opts:['Onjuist','Juist'],exp:'De meeste TMD-gevallen zijn zelfbeperkend en niet progressief. Echte progressieve gewrichtsschade is zeldzaam en geassocieerd met systemische artritis.'},
  {q:'Een dikke opbeetplaat geeft meer ontspanning van de kaakspieren. Juist of onjuist?',opts:['Onjuist','Juist'],exp:'Dikte van de opbeetplaat heeft geen directe relatie met spierontspanning; de occlusale stabiliteit en verhoogde verticale dimensie bepalen het effect.'},
]},

// ═══ ORALE PATHOLOGIE 2024 JUNI (15 vragen) ═══
pato_cikmis_2024juni:{title:'Orale Pathologie/Oncologie Cikmis – 2024 Juni',questions:[
  {q:'Ameloblastoom komt vaker voor in de onderkaak dan de bovenkaak. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Ameloblastoom: 80% in de mandibula, met name in het molaargebied. Bovenkaak (20%) heeft slechtere prognose door nabijheid schedelbasis.'},
  {q:'Een tumor in de sinus maxillaris kan traanogen veroorzaken. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Maxillaire sinustumor kan de ductus nasolacrimalis comprimeren, wat leidt tot tranen-afvoerbelemmering en epifora.'},
  {q:'Erythroplakje heeft een ...',opts:['Hoog risico op maligne transformatie (maligne of pre-maligne)','Laag risico op maligne transformatie'],exp:'Erythroplakje: 90% is dysplastisch of al maligne bij biopsie. Hogere malignisatiekans dan leukoplakje.'},
  {q:'Plaveiselcelcarcinoom van de mond verspreidt zich via ...',opts:['Lymfklieren','Hematogene weg als eerste'],exp:'Orale carcinomen: regionale lymfkliermetastasen (N-stadium) zijn primaire verspreidingsroute. Hematogeen verspreiding is latere fase.'},
  {q:'Metastasen van oraal carcinoom worden het meest gevonden in de ...',opts:['Kaakhoek/ondermolaar regio (level I-II lymfklieren)','Supraclaviculaire lymfklieren'],exp:'Orale carcinomen metastaseren eerst naar ipsilaterale submandibulaire en bovenste jugulaire lymfklieren (level I en II).'},
  {q:'Subperiostale abcessen geven weinig pijn. Juist of onjuist?',opts:['Onjuist','Juist'],exp:'Subperiostale abcessen zijn juist ZEER pijnlijk door druk onder het periost (rijk geinerveerd). Fluctuatie treedt later op.'},
  {q:'Osteoradionecrose is een ...',opts:['Late bijwerking van radiotherapie','Vroege bijwerking van radiotherapie'],exp:'Osteoradionecrose: door vasculaire schade en fibrose na radiotherapie; treedt vaak maanden tot jaren later op, niet acuut.'},
  {q:'Welke aandoening toont een klinisch beeld van roodheid zonder zichtbare afwijkingen in het mondslijmvlies?',opts:['Mondbranden (burning mouth syndrome)','Erythroplakje'],exp:'Burning mouth syndrome: brandende pijn zonder klinisch zichtbare afwijkingen. Erythroplakje is WEL zichtbaar als rode laesie.'},
  {q:'Kanker ontstaat primair door ...',opts:['DNA-schade (mutaties in oncogenen en tumorsuppressorgenen)','Virussen alleen'],exp:'Carcinogenese: accumulatie van somatische mutaties in DNA door o.a. tabak, alcohol, straling, virussen (HPV). Multistep-model.'},
  {q:'Plaveiselcelcarcinoom van de mond komt voornamelijk voor bij ...',opts:['Oudere mensen (> 50 jaar, meer bij mannen)','Jonge mensen < 30 jaar'],exp:'Klassiek orale SCC: man > 50 jaar, tabak + alcohol. Toename bij jongen door HPV-gerelateerde orofaryngeale SCC.'},
  {q:'Leukoplakie wordt vooral gevonden bij mensen ouder dan ...',opts:['40 jaar','20 jaar'],exp:'Leukoplakie: incidentie neemt toe met leeftijd; zeldzaam onder 40 jaar. Risicofactoren zijn tabak, alcohol, chronische irritatie.'},
  {q:'De voorkeurslokalisatie van folliculaire cyste is ...',opts:['Bovenste M3 en onderste cuspidaat','Onderste M3 en bovenste cuspidaat'],exp:'Folliculaire cyste (denticulaire cyste): ontstaat rondom kroon van niet-doorgebroken tand; meest bij OK-M3 en BK-cuspidaat.'},
  {q:'Fordyce spots zijn ...',opts:['Ectopische talgklieren in het mondslijmvlies (normaal, geen behandeling nodig)','Witte laesies door HPV-infectie'],exp:'Fordyce spots: geelwitte puntjes, ectopische talgklieren op wangslijmvlies en lippen. Normaal anatomische variant, goedaardig.'},
  {q:'Behandeling van tong-dysplasie is ...',opts:['Lokale excisie','Radiotherapie'],exp:'Dysplasie van de tong: chirurgische excisie met vrije marges. Follow-up essentieel wegens recidiefrisico.'},
  {q:'Focale scleroserende osteomyelitis wordt behandeld door ...',opts:['Afwachten (watchful waiting)','Curettage'],exp:'Focale scleroserende osteomyelitis = reactief dense bot bij chronische laaggraadse pulpitis; asymptomatisch, geen behandeling nodig, wel monitoring.'},
]},

// ═══ ORTHODONTIE 2024 JUNI (15 vragen) ═══
ortho_cikmis_2024juni:{title:'Orthodontie Cikmis – 2024 Juni',questions:[
  {q:'Orthodontische behandeling bij volwassenen is moeilijker vanwege ...',opts:['Geen groei meer, langzamere botombouw en meer complicatierisico','Volwassenen zijn minder gemotiveerd dan kinderen'],exp:'Volwassenen: geen sutuurgroei, langzamere alveolaire remodellering, meer kans op wortelresorptie en paro-problemen bij behandeling.'},
  {q:'Buitenboordbeugel (headgear): is er verschil in effect tussen meisjes en jongens?',opts:['Nee, bij meisjes en jongens is er geen significant verschil in effect','Ja, meisjes reageren beter vanwege eerdere groeispurt'],exp:'Headgear-effect is afhankelijk van groeifase, niet direct van geslacht; timing t.o.v. piek groeispurt is bepalend.'},
  {q:'Een 12-jarige met diepe beet en weinig motivatie: wat doe je?',opts:['Uitleggen en motivatie verhogen; behandeling uitstellen tot patient gemotiveerd is','Onmiddellijk starten met behandeling'],exp:'Orthodontische behandeling vereist actieve medewerking; bij een niet-gemotiveerde patient is behandeling ineffectief en kan worden uitgesteld.'},
  {q:'Extractie van een blijvende molaar bij 8-jarige: wanneer is het juiste moment?',opts:['Wanneer furcatie van de opvolgende premolaar zichtbaar is op rontgenfoto','Na volledig doorbreken van de eerste premolaar'],exp:'Balansextractie: juiste timing is wanneer furcatie van de tweede premolaar zichtbaar is op rontgenfoto, zodat migratieruimte goed wordt benut.'},
  {q:'Serie-extractie bij kinderen houdt in ...',opts:['Gecontroleerde verwijdering van melkelementen en eventueel blijvende elementen om ruimte te creeren','Extractie van alle melkelementen tegelijk'],exp:'Serie-extractie: sequentiele verwijdering (melkcuspidaten, eerste melkmolaren) gevolgd door eerste premolaren om ruimte voor cuspidaten te maken.'},
  {q:'In Nederland gebruiken we bij fronttand-spalken bij avulsie bij voorkeur een spalk van ...',opts:['12-22 (beide laterale incisieven als ankerpunten)','13-23 (cuspidaten als ankerpunten)'],exp:'Nederlandse richtlijn (NVE): fronttandspalk 12-22; cuspidaten hebben te grote wortels en krachten voor spalkankers.'},
  {q:'Bij schisis (palatoschisis) is de bovenkaak minder gegroeid. Juist of onjuist?',opts:['Juist','Onjuist'],exp:'Schisis-patienten: littekenweefsel na chirurgische sluiting beperkt de sagittale en transversale maxillaire groei, leidend tot klasse III.'},
  {q:'Bij het ontbreken van element 35: wanneer wacht je op de aanleg van 75?',opts:['Afwachten tot na 3/4 wortelvorming van de tweede premolaar','Direct 75 verwijderen om ruimte te sluiten'],exp:'Als 35 aangelegd is maar traag ontwikkelt: melkmolaar 75 behouden tot 3/4 wortelvorming van 35 zichtbaar is voor goede doorbraakprognose.'},
  {q:'Orthodontische extrusie kan altijd worden uitgevoerd. Juist of onjuist?',opts:['Onjuist','Juist'],exp:'Orthodontische extrusie is gecontra-indiceerd bij onvoldoende bot, ankylose, of als de kroon-wortelverhouding na extrusie ongunstig wordt.'},
  {q:'Sagittale kaakgroei stopt bij vrouwen gemiddeld op welke leeftijd?',opts:['18-20 jaar (vrouwen); mannen 20-25 jaar','25 jaar bij beiden'],exp:'Vrouwen: sagittale groei grotendeels voltooid rond 18 jaar. Mannen groeien langer door tot ca. 20-25 jaar. Relevant voor timing orthodontie.'},
  {q:'Bij een meisje van 10 jaar: welke tanden zijn dan normaal zichtbaar in de mond?',opts:['Ondercuspidaten kunnen al zichtbaar zijn','Alle blijvende tanden inclusief premolaren zijn al aanwezig'],exp:'10-jarig meisje: 6en, 1en, 2en, en soms al 3en (ondercuspidaten) doorgebroken. Premolaren doorbreken rond 10-12 jaar.'},
  {q:'Een Bollard-anker wordt gebruikt bij ...',opts:['Kaakgroeibeeinvloeding (orthopedisch anker in os)','Tandboogverbreding'],exp:'Bollard-implantaat: mini-implantaat in bot als absoluut anker voor orthopedische krachten (bijv. protractie maxilla bij schisis).'},
  {q:'Een 13-jarig meisje bij controle heeft matige mondhygiene. Wat is uw prioriteit?',opts:['Motiveren en mondhygiene-instructie geven voor start van behandeling','Direct starten met orthodontische behandeling'],exp:'Goede mondhygiene is voorwaarde voor orthodontische behandeling; brackets verhogen plaqueopbouw en cariesrisico.'},
  {q:'Afwezigheid van een bovenhoektand (C-sup) wordt het vaakst veroorzaakt door ...',opts:['Impactie (niet doorbreking)','Agenese (aanlegstoornis)'],exp:'Bovenhoektanden zijn na verstandskiezen het vaakst geimpacteerd (palatinaal in 85% van gevallen). Agenese van C-sup is zeldzaam.'},
  {q:'Bij een 6-jarige: element 11 is doorgebroken maar na 1 jaar is 21 nog niet doorgebroken. Wat doe je?',opts:['Rontgenfoto maken om aanleg en positie te beoordelen','Nog 6 maanden afwachten'],exp:'Asymmetrische doorbraak van centrale incisieven: meer dan 6 maanden verschil vereist rontgenonderzoek (impactie, odontoom, diasteem).'},
]},

};
window.QUIZZES = Object.assign(window.QUIZZES || {}, sets);
})();
