/* =================================================================
   data_cikmis_2018_2019.js
   Cikmis sorular – 2018 December + 2019 December/September
   opts[0] = ALTIJD het CORRECTE antwoord. quiz.js shuffelt bij weergave.
   ================================================================= */
(function(){
var sets = {

// ══════════════════════════════════════════════════════════════════
// THK1 – 2018 DECEMBER
// ══════════════════════════════════════════════════════════════════

cario_cikmis_2018dec:{
  title:"Cariologie Cikmis – 2018 December",
  questions:[
    {q:"Een kenmerkend aspect van een INACTIEVE carieslaesie in het glazuur is:",
     opts:["Een glimmend wit oppervlak","Een dof ruw oppervlak","Een bruine zachte laesie","Een zwarte caviteit"],
     exp:"Inactieve caries = geremineraliseerd, glad/glimmend, hard oppervlak. Actieve caries is dof en ruw."},
    {q:"De excavatiegrens van occlusale caries in dentine ligt bij:",
     opts:["Het geinfecteerde dentine, waarbij het gedemineraliseerde dentine wordt verwijderd","Uitsluitend het geinfecteerde dentine behouden","Alle zachte dentine verwijderen inclusief gezond dentine","Het enamel-dentine overgang"],
     exp:"Excavatie tot de grens van het geinfecteerde dentine. Gedemineraliseerd maar niet-geinfecteerd dentine kan remineraliseren en wordt bewaard."},
    {q:"Wanneer kan een fluoridegel bij kinderen gebruikt worden als extra cariespreventiemiddel?",
     opts:["Als andere preventieve maatregelen bij het kind niet voldoende werken","In principe kan dit altijd bij de halfjaarlijkse controle worden ingezet","Uitsluitend bij kinderen onder 6 jaar","Alleen bij melkgebit"],
     exp:"Fluoridegel is een extra maatregel wanneer reguliere preventie (poetsen, dieet) onvoldoende is."},
    {q:"Fissuurcaries in een 36 scoort 3 op de Ekstrand-schaal. Twee jaar later score 4. Wat is de beste aanpak?",
     opts:["De 36 caveren en restaureren","Via een sealant het cariesproces laten remineraliseren","Afwachten en over 2 jaar opnieuw beoordelen","Fluoride applicatie en herevaluatie na 6 maanden"],
     exp:"Ekstrand score 4 = cavitatie in dentine. Dit is een indicatie voor invasieve behandeling: caviteren en restaureren."},
    {q:"Ontstoken gingiva (bloeding bij sonderen) naast een proximale initiele carieslaesie – wat betekent dit?",
     opts:["Actief cariesproces waarbij extra preventiemaatregelen nodig zijn","Actief cariesproces met caviteit","Inactief cariesproces, geen actie nodig","Alleen gingivitisbehandeling noodzakelijk"],
     exp:"Bloeding bij sonderen naast een initiele laesie wijst op een actief cariesproces. Extra preventie is aangewezen, geen directe restauratie."},
    {q:"U wilt de basissamenstelling van de tandplaque beinvloeden zodat de flora minder cariogeen wordt. De meest effectieve maatregel is:",
     opts:["Minder vaak snoepen (reduceren van fermenteerbare koolhydraten)","Beter en vaker poetsen","Meer water drinken","Fluoride tandpasta gebruiken"],
     exp:"De suikerfrequentie (snackgedrag) bepaalt de ecologische druk op de flora. Minder snoepen = minder zuurproductie = minder cariogene flora."},
    {q:"In welk stadium van occlusale caries in een 25 is rontgenfoto het meest diagnostisch zinvol?",
     opts:["Als de caries net het dentine heeft bereikt","Zodra glazuurcaries zichtbaar is","Wanneer de caries reeds de pulpa heeft bereikt","Bij elke controle ongeacht het stadium"],
     exp:"Rontgenfoto is het meest zinvol bij dentinecaries omdat glazuurcaries klinisch beter te detecteren is. Bij dentinecaries kan invasief ingrijpen nog beperkt blijven."},
    {q:"Wat is de beste methode om progressie van initiele caries tijdens de doorbraak van een eerste blijvende molaar te voorkomen?",
     opts:["Goed poetsen met fluoridehoudende tandpasta","Lokaal fluoridevloeistof aanbrengen","Fissuursealing direct na doorbraak","Fluoride gel applicatie 2x per jaar"],
     exp:"Poetsen met fluoridehoudende tandpasta is de bewezen meest effectieve methode; dit compenseert ook voor slechte bereikbaarheid."},
    {q:"Bij een buccale wortelcarieslaesie volledig omgeven door dentine, wat is de juiste volgorde bij excavatie?",
     opts:["Eerst de carieuze dentine outline schoonmaken, dan het centrale deel","Eerst het centrale carieuse deel verwijderen en dan de outline","Tegelijk centrale deel en outline verwijderen","Geen volgorde; verwijder alles in een keer"],
     exp:"De outline (wanden) worden eerst geprepareerd om goede retentievormen te verkrijgen; daarna het centrale deel excaven."},
    {q:"Cariespredilectieplaatsen kenmerken zich door:",
     opts:["Plaqueophoping, lage speekselstroom, ecologische niche","Weinig plaque, waterige speekselstroom, EPS","Hoge speekselstroom, hoge pH, veel poetsen","Fluoridegebrek, hoge suikerinname, geen niche"],
     exp:"Predilectieplaatsen: combinatie van plaqueretentie (niche), verminderde zelfreiniging (lage speekselstroom) en ecologische druk."},
    {q:"De belangrijkste reden dat posterieure composietrestauraties falen is:",
     opts:["Secundaire caries of breuk van de restauratie","Slijtage en verkleuring van de restauratie","Polymerisatiekrimp","Randlekkage zonder breuk"],
     exp:"Klinische studies tonen dat secundaire caries en fractuur de voornaamste faaloorzaken zijn bij posterieure composieten."},
    {q:"De primer van een zelf-etsend hechtingssysteem is hydrofoob. Juist of onjuist?",
     opts:["Onjuist – de primer is hydrofiel","Juist – de primer is hydrofoob","Juist – zelf-etsende primers zijn altijd hydrofoob","Onjuist – primers hebben geen hydrofobe of hydrofiele eigenschappen"],
     exp:"De primer van een zelf-etsend systeem is HYDROFIEL: hij moet in het vochtige dentine penetreren. Het adhesief (bond) is hydrofoob."},
    {q:"Op welk type reactie is de uitharding van glasionomeercement gebaseerd?",
     opts:["Zuur-base reactie","Lichtinduceerde fotopolymerisatie","Chemische polymerisatie van monomeren","Hydrolyse van silicaten"],
     exp:"GIC hardt uit via een zuur-base reactie: polyacrylinezuur (zuur) reageert met aluminosilicaatglas (base)."},
    {q:"Vloeibare composieten hebben volumetrische krimp maar minder sterk dan conventionele composieten. Juist of onjuist?",
     opts:["Onjuist – flowables hebben MEER krimp door hogere harsinhoud","Juist – flowables krimpen minder dan conventioneel composiet","Juist – flowables hebben gelijke krimp maar betere vloei","Onjuist – beide composiettypen hebben identieke krimp"],
     exp:"Flowable composieten bevatten meer harsmatrix en MINDER vulstof, waardoor zij MEER polymerisatiekrimp vertonen dan conventionele composieten."},
    {q:"Voor hechting aan glazuur gaat de voorkeur uit naar:",
     opts:["30-40 seconden fosforzuuretsing (totaaletsing)","15 seconden aanbrengen van een zelf-etsende primer","Alleen primer zonder etsing","HEMA-bevattend adhesief zonder etsing"],
     exp:"Aan glazuur geeft totaaletsing met fosforzuur (30-40 sec) de hoogste hechtingssterkte. Zelf-etsende primers presteren minder op glazuur."}
  ]
},

endo_cikmis_2018dec:{
  title:"Endodontologie Cikmis – 2018 December",
  questions:[
    {q:"Bij kroonpreparaties van premolaren is er het meest gevaar voor het ... pulpahoorn.",
     opts:["Buccale pulpahoorn van de bovenste premolaar","Palatinale pulpahoorn","Occlusale pulpahoorn","Mesiale pulpahoorn van de onderpremolaar"],
     exp:"Bij de bovenpremolaar ligt het buccale pulpahoorn hoog en is vatbaar voor perforatie bij kroonpreparatie."},
    {q:"Bij een interne wortelresorptie is aangewezen:",
     opts:["Pulpectomie en wortelkanaalbehandeling","Partiële pulpotomie","Directe pulpakap","Extractie"],
     exp:"Interne resorptie = ongecontroleerde klastische activiteit in het kanaal. Volledige WKB is nodig om de pulpa te verwijderen en de resorptie te stoppen."},
    {q:"De endodontische opening bij een bovenmolaar ligt t.o.v. de bodem van de pulpakamer:",
     opts:["Iets mesiaal en vestibulair","Iets distaal en palatinaal","Centraal in de pulpakamer","Palatinaal vlak"],
     exp:"De mesiobuccale, distobuccale en palatinale kanaalingangen vormen een driehoek; de geometrisch meest centrale opening ligt iets mesiaal-vestibulair."},
    {q:"Het risico op vijlbreuk bij roterende instrumenten neemt significant toe als:",
     opts:["Vijlen niet dragend het kanaal worden ingebracht","Geen smeermiddel wordt gebruikt","Te snel gedraaid wordt","De apex open is"],
     exp:"Roterende vijlen moeten altijd roterend worden ingebracht; een niet-roterende inbreng genereert torsiebreuk. Smeermiddel is ook belangrijk maar minder critisch."},
    {q:"Een apicaal litteken na WKB:",
     opts:["Ontstaat als het periapicale ontstekingsweefsel wordt vervangen door cel-arm bindweefsel","Ontstaat altijd na een chirurgische ingreep waarbij beenweefsel wordt verwijderd","Is een teken van mislukte behandeling","Verkalkt altijd na verloop van tijd"],
     exp:"Een apicaal litteken = cel-arm bindweefsel vervangt het ontstekingsweefsel. Op rontgen: scherp begrensde radiolucency die niet verkleint."},
    {q:"Een 47 reageert niet op koude, is licht percussiegevoelig, en op rontgenfoto is er verbreding van het parodontale ligament. De meest waarschijnlijke diagnose is:",
     opts:["Niet-pijnlijke parodontitis apicalis","Niet-pijnlijke irreversibele pulpitis","Reversibele pulpitis","Acute dento-alveolaire abces"],
     exp:"Geen vitaliteitsreactie (koude negatief) + APD-verbreding + percussiegevoelig = parodontitis apicalis (symptomatisch of asymptomatisch)."},
    {q:"De prognose van een WKB wordt grotendeels bepaald door:",
     opts:["De eindgrens van de wortelkanaalvulling","De gebruikte vultechniek","De instrumentatiemethode","De keuze van sealant"],
     exp:"De apicale afsluitkwaliteit en de eindgrens (0,5-1mm van apex) zijn de sterkste prognostische factoren bij WKB."},
    {q:"Een steriele pulpanecrose kan ontstaan als gevolg van:",
     opts:["Een mechanisch trauma","Een carieslaesie","Een periocontale infectie","Fluorideoverdosering"],
     exp:"Traumatische pulpanecrose kan steriel zijn: geen bacteriele invasie, maar ischemische necrose door onderbreking van de bloedtoevoer."},
    {q:"Het dichtgroeien van wortelkanalen is synoniem voor:",
     opts:["Obliteratie","Apicale constrictie","Interne resorptie","Calciumhydroxide inducering"],
     exp:"Obliteratie = geleidelijk dichtgroeien (verkalken) van het pulpalumen. Te zien als verdwijnen van de kanaallijn op rontgenfoto."},
    {q:"De behandeling van reversibele pulpitis berust op:",
     opts:["Indirect pulp capping (verwijderen van de oorzaak, beschermen gezond dentine)","Pulpotomie","Pulpectomie","Directe pulpakap met MTA"],
     exp:"Reversibele pulpitis: verwijder de stimulus (caries, fractuur) en breng een kalmerend verbandmateriaal aan. Indirect pulp capping."},
    {q:"Om smeer-laag (smear layer) te verwijderen wordt gebruikt:",
     opts:["17% EDTA","7% natriumhypochloriet","Chloorhexidine 2%","Calciumhydroxide pasta"],
     exp:"EDTA 17% is een chelator en verwijdert de anorganische smear layer. NaOCl verwijdert organisch debris maar niet de smear layer."},
    {q:"Het natriumhypochloriet-accident treedt het meest op in geval van:",
     opts:["Een irrigatienaald die strak vast raakt in het kanaal","Een open apex","Gebruik van te hoge concentratie NaOCl","Te snelle irrigatie"],
     exp:"Wanneer de irrigatienaald inklemd raakt, kan NaOCl onder druk worden geinjiceerd voorbij de apex. Altijd passend losse naald gebruiken."},
    {q:"Een crown-down preparatietechniek wordt gebruikt om:",
     opts:["Te voorkomen dat de geinfecteerde kanaalinhoud door het apicale foramen wordt geprest","Coronaal zoveel mogelijk tandweefsel te besparen","De apex snel te bereiken","Instrumentbreuk te voorkomen"],
     exp:"Crown-down: van coronaal naar apicaal prepareren. Verwijdert eerst de coronate bacterielast, vermindert apicale extrusie van debris."},
    {q:"Welk wondverband geeft een betere prognose bij pulpotomie van een melktand?",
     opts:["MTA (Mineral Trioxide Aggregate)","Calciumhydroxide Ca(OH)2","Zinkoxide-eugenol","Formocresol"],
     exp:"MTA geeft betere pulpagenezingsrespons dan calciumhydroxide bij pulpotomie, met minder interne resorptie als complicatie."},
    {q:"DETI score A wordt vastgesteld wanneer:",
     opts:["Geen van de criteria uit het DETI-formulier van toepassing is","Slechts een van de criteria van toepassing is","Alle criteria van toepassing zijn","Score B niet van toepassing is"],
     exp:"DETI score A: geen enkel criterium van toepassing. DETI score B: een of meer criteria aanwezig, aanvullend CEB-formulier invullen."}
  ]
},

paro_cikmis_2018dec:{
  title:"Parodontologie Cikmis – 2018 December",
  questions:[
    {q:"Waarvoor dient de DPSI?",
     opts:["Om globaal overzicht te krijgen van parodontale problemen","Om een definitieve diagnose parodontitis te stellen","Om de furcatie te meten","Om de BOP te registreren"],
     exp:"DPSI (Dutch Periodontal Screening Index) geeft een globale screening. Geen diagnose-instrument maar een triage-hulpmiddel."},
    {q:"Er moet tandsteen aanwezig zijn om een DPSI 3- score te geven. Juist of onjuist?",
     opts:["Onjuist – tandsteen is niet verplicht voor DPSI 3-","Juist – DPSI 3- vereist subgingivaal tandsteen","Juist – tandsteen bepaalt de DPSI-score","Onjuist – tandsteen geeft automatisch DPSI 4"],
     exp:"DPSI 3- = pocket 3,5-5,5mm met bloeding, ongeacht tandsteen. Tandsteen is een extra bevinding maar geen vereiste voor de score."},
    {q:"De meest gebruikte manier om de distale furcatie van een 16 te meten is vanuit:",
     opts:["Palatinaal","Vestibulair","Mesiaal","Distaal"],
     exp:"Bij een bovenmolaar (16) wordt de distale furcatie het best bereikt vanuit palatinaal met de furcatiepeilsonde."},
    {q:"De meeste kans op een wortelgroef bij de 26 is bij:",
     opts:["De mesiale wortel","De distale wortel","De palatinale wortel","Alle wortels gelijk"],
     exp:"Wortelgroeven komen het meest voor op de mesiale wortel van bovenmolaren, wat kan bijdragen aan lokale parodontale afbraak."},
    {q:"Om tandsteen te voorkomen wordt aan tandpasta toegevoegd:",
     opts:["Pyrofosfaten","Zuur","Fluoride in hoge concentratie","Calciumperoxide"],
     exp:"Pyrofosfaten (en tripolyfosfaat, hexametafosfaat) binden aan calcium en remmen zo de kristallisatie van calciumfosfaat (tandsteen)."},
    {q:"Diabetes mellitus en parodontitis zijn niet gerelateerd. Juist of onjuist?",
     opts:["Onjuist – er is een bidirectionele relatie tussen DM en parodontitis","Juist – DM en parodontitis zijn onafhankelijk","Juist – alleen type I DM heeft een relatie met paro","Onjuist – alleen parodontitis beinvloedt DM, niet andersom"],
     exp:"Er is een bidirectionele relatie: DM vergroot het risico op paro, en paro-behandeling kan glycemische controle verbeteren."},
    {q:"Verlies van meer dan de helft van de wortellengte geeft een redelijke prognose. Juist of onjuist?",
     opts:["Onjuist – meer dan 50% botverlies geeft een slechte prognose","Juist – 50% botverlies geeft nog een redelijke prognose","Juist – prognose hangt alleen af van mobiliteitsgraad","Onjuist – prognose hangt alleen af van furcatiebetrokkenheid"],
     exp:"Meer dan 50% botverlies wordt geclassificeerd als slechte prognose (twijfelachtig tot hopeloos), niet redelijk."},
    {q:"Aanhechtingsverlies wordt bepaald door pocketdiepte. Juist of onjuist?",
     opts:["Onjuist – aanhechtingsverlies = pocketdiepte + recessie (afstand CEJ tot pocket)","Juist – pocketdiepte is gelijk aan aanhechtingsverlies","Juist – beide zijn hetzelfde als er geen recessie is","Onjuist – aanhechtingsverlies wordt bepaald door botafbraak op rontgen"],
     exp:"Klinisch aanhechtingsverlies (CAL) = pocketdiepte + recessie of minus positieve gingivastand. Niet hetzelfde als pocketdiepte."},
    {q:"Mobiliteit meer dan 1mm horizontaal is mobiliteitsgraad 2. Juist of onjuist?",
     opts:["Juist – graad 2 = meer dan 1mm horizontale mobiliteit","Onjuist – graad 2 = meer dan 2mm","Onjuist – graad 2 = elke horizontale mobiliteit","Juist – maar alleen als er ook verticale mobiliteit is"],
     exp:"Miller graad 1 = tot 1mm horizontaal. Graad 2 = meer dan 1mm horizontaal. Graad 3 = meer dan 2mm of verticale mobiliteit."},
    {q:"Als een patient na controle een plaqueindex van minder dan 15% heeft, hoeft geen mondhygieneinstructie gegeven te worden. Juist of onjuist?",
     opts:["Onjuist – mondhygieneinstructie blijft onderdeel van elke paro-controle","Juist – 15% is de drempelwaarde","Juist – onder 15% is verdere instructie niet zinvol","Onjuist – de drempelwaarde is 20%"],
     exp:"Mondhygieneinstructie blijft relevant bij elke controle, ongeacht de plaqueindex. Positieve reinforcement en onderhoud zijn altijd nodig."},
    {q:"Tandsteen op een implantaat zit minder vast dan op een natuurlijk element. Juist of onjuist?",
     opts:["Juist – tandsteen hecht minder sterk op het titanium oppervlak","Onjuist – tandsteen hecht sterker op implantaten","Onjuist – de hechting is gelijk","Juist – maar dit is klinisch niet relevant"],
     exp:"Tandsteen hecht minder stevig op het geoxideerde titaniumoppervlak dan op tandoppervlakken. Desondanks beinvloedt het peri-implantaire gezondheid."},
    {q:"Gingivitis en tandsteen zijn beiden zichtbaar op rontgenfoto. Juist of onjuist?",
     opts:["Onjuist – gingivitis is NIET zichtbaar op rontgenfoto, alleen supragingivaal tandsteen is dat","Juist – beide zijn zichtbaar","Onjuist – tandsteen is ook niet zichtbaar","Juist – gingivitis toont als verbreed parodontaalspleet"],
     exp:"Gingivitis is een zachteweefselontsteking: NIET te zien op rontgen. Supragingivaal tandsteen kan als radieopaque lagen zichtbaar zijn."},
    {q:"Na initiele parodontale behandeling daalt de bacteriecount in de pocket van 10.000.000 naar 100.000. Juist of onjuist?",
     opts:["Juist – scaling en rootplaning reduceert de bacterielast met 99% (2 log reducties)","Onjuist – de bacteriecount daalt nauwelijks","Onjuist – de count daalt naar minder dan 1000","Juist – maar dit duurt meer dan 3 maanden"],
     exp:"Na SRP daalt de bacterieload met 99-99,9% (2-3 log). Van 10^7 naar 10^5 is een reductie van 2 log. Klinisch correcte schatting."},
    {q:"Na 1 jaar kunt u een meetbare pocketreductie na chirurgische parodontale behandeling aantonen. Juist of onjuist?",
     opts:["Juist – na 1 jaar zijn de resultaten van paro-chirurgie stabiel en meetbaar","Onjuist – je kunt pas na 6 maanden meten","Onjuist – paro-chirurgie geeft geen meetbare reductie","Juist – maar alleen bij resectieve chirurgie"],
     exp:"Her-evaluatie na paro-chirurgie vindt plaats na 3-6 maanden. Na 1 jaar zijn de resultaten goed te beoordelen en stabiel."}
  ]
},

pedo_cikmis_2018dec:{
  title:"Kindertandheelkunde Cikmis – 2018 December",
  questions:[
    {q:"Een motorisch ontwikkeld kleuter kan prima zelf zelfstandig zijn tanden poetsen. Juist of onjuist?",
     opts:["Onjuist – volledig zelfstandig poetsen kan gemiddeld pas vanaf 10 jaar","Juist – kleuters kunnen goed poetsen","Juist – zelfstandig poetsen kan vanaf 6 jaar","Onjuist – kinderen kunnen nooit zelfstandig poetsen"],
     exp:"Fijne motoriek voor effectief zelfstandig poetsen ontwikkelt zich gemiddeld rond 10 jaar. Tot dan is begeleiding door ouders noodzakelijk."},
    {q:"U ziet een fisteluitgang boven een donker verkleurde 51 bij Juri (5 jaar). Er zijn geen klachten maar Juri is erg bang. Wat doet u?",
     opts:["Afspraak maken voor extractie van de 51","Afwachten zolang er geen klachten zijn","Antibiotica voorschrijven","Wortelkanaalbehandeling van de 51 starten"],
     exp:"Een fistel bij een melktand met pulpanecrose is een indicatie voor extractie, ook zonder klachten. De infectie kan de onderliggende blijvende tandkiem beschadigen."},
    {q:"Communicatie met een kind verloopt gemiddeld voor 50% verbaal en 50% non-verbaal. Juist of onjuist?",
     opts:["Onjuist – bij kinderen is non-verbale communicatie groter dan 50%","Juist – 50/50 verhouding","Onjuist – het is 90% verbaal","Juist – afhankelijk van de leeftijd van het kind"],
     exp:"Communicatie met kinderen is voor een groot deel non-verbaal (lichaamstaal, gezichtsuitdrukkingen, toon). Bij jonge kinderen kan dit 70% of meer zijn."},
    {q:"Wat adviseert het Basisadvies Fluoride voor kinderen van 0-1 jaar?",
     opts:["Vanaf doorbraak eerste tand 2x per dag poetsen met fluoridepeutertandpasta (500-750 ppm)","Vanaf doorbraak eerste tand 1x per dag poetsen met fluoridepeutertandpasta","Geen fluoride onder 1 jaar","Fluoridedruppels geven vanaf de geboorte"],
     exp:"Het Ivoren Kruis Basisadvies: vanaf doorbraak eerste tand 2x daags poetsen met peutertandpasta 500-750 ppm fluoride. Ouders uitvoeren."},
    {q:"De wortels van melkelementen resorberen onregelmatig. Juist of onjuist?",
     opts:["Juist – fysiologische wortelresorptie van melkelementen verloopt onregelmatig","Onjuist – resorptie verloopt altijd gelijkmatig","Onjuist – resorptie begint altijd apicaal","Juist – maar alleen bij pathologische resorptie"],
     exp:"Fysiologische resorptie van melktandwortels verloopt onregelmatig en asymmetrisch. Dit is normaal en hoeft niet behandeld te worden."},
    {q:"De insteekplek voor mandibulaire anesthesie bij kinderen is vergeleken met volwassenen:",
     opts:["Hoger dan bij volwassenen","Lager dan bij volwassenen","Op dezelfde hoogte","Varieert per kind"],
     exp:"Bij kinderen ligt de mandibulaire foramen hoger t.o.v. de occlusaalvlak. Anesthesie moet dus hoger worden toegediend dan bij volwassenen."},
    {q:"Een kaasmolaar (MIH) is:",
     opts:["Meer vatbaar voor caries door glazuurdefecten","Minder vatbaar voor caries","Even vatbaar als normale kiezen","Alleen gevoelig voor erosie"],
     exp:"Molaar-Incisief Hypomineralisatie (MIH / kaasmolaar): het aangedane glazuur is poreus en hypomineraliseerd, waardoor het meer vatbaar is voor caries en fracturen."},
    {q:"Bij een moeilijk behandelbaar kind dat de behandeling weigert, helpt het om structuur en grenzen te bieden. Juist of onjuist?",
     opts:["Juist – duidelijke structuur en consistente grenzen geven veiligheid aan angstige kinderen","Onjuist – grenzen stellen verhoogt de angst","Onjuist – afleidingstechnieken zijn effectiever","Juist – maar alleen bij kinderen boven 8 jaar"],
     exp:"Tell-show-do in combinatie met duidelijke structuur en grenzen is effectief bij gedragsproblemen. Predictabiliteit geeft het kind houvast."},
    {q:"Een kind heeft twee kiezen laten trekken vanwege caries, twee approximale caviteiten en een occlusale cariesleasie. Wat is de dMFT-score?",
     opts:["5 (2 extracties + 2 approximale + 1 occlusale)","3 (alleen de extracties tellen)","2,5","2"],
     exp:"dMFT: 2 geextraheerde kiezen (M=2) + 2 caviteiten (F=2) + 1 caviteit (F=1). Totaal dMFT = 5. Elke geextraheerde tand of caviteit telt als 1."},
    {q:"Voor gebitsontwikkeling is het behoud van welk element het meest belangrijk?",
     opts:["Tweede ondermolaar (75/85)","Tweede bovenmolaar","Eerste ondermolaar","Eerste bovenmolaar"],
     exp:"De tweede melkmolaar (75/85) is ruimtehouder voor de tweede premolaar. Prematuur verlies leidt tot ruimteverlies. In onderkaak is dit kritischer."}
  ]
},

speeksel_cikmis_2018dec:{
  title:"Speeksel Cikmis – 2018 December",
  questions:[
    {q:"Kauwen stimuleert de speekselproductie. Juist of onjuist?",
     opts:["Juist – kauwen stimuleert reflex-speekselsecretie via de parasympathicus","Onjuist – kauwen heeft geen effect op speekselsecretie","Onjuist – alleen geur en smaak stimuleren speeksel","Juist – maar alleen bij suikerhoudend voedsel"],
     exp:"Mechanische kauwprikkels activeren de parasympathische innervatie van de speekselklieren, wat leidt tot verhoogde waterige speekselsecretie."},
    {q:"Er zijn geen speekselklieren in het verhemelte. Juist of onjuist?",
     opts:["Onjuist – er zijn kleine accessoire speekselklieren in het palatum","Juist – het palatum heeft geen speekselklieren","Onjuist – de gl. palatinae zijn de grootste speekselklieren","Juist – het verhemelte heeft alleen mucosacellen"],
     exp:"Het palatum durum en molle bevatten talrijke kleine accessoire muceuze speekselklieren (glandulae palatinae)."},
    {q:"Xerostomie stimuleert de speekselproductie. Juist of onjuist?",
     opts:["Onjuist – xerostomie IS de droge mond, dus verlaagde speekselproductie","Juist – droge mond activeert compensatiemechanismen","Onjuist – xerostomie heeft geen effect op speekselklieren","Juist – reflectoir meer speeksel bij xerostomie"],
     exp:"Xerostomie = subjectief droge mond, geassocieerd met verminderde speekselsecretie (hyposalivatie). Het is een gevolg, geen oorzaak."},
    {q:"Een mucocele komt vaak voor in de bovenlip. Juist of onjuist?",
     opts:["Onjuist – mucocele is het meest frequent in de onderlip","Juist – de bovenlip is de voorkeurslocatie","Onjuist – mucocele komt alleen voor in de mondbodem (ranula)","Juist – maar ook veel in de wangen"],
     exp:"Mucocele (speekselcyste door ductusruptuur) is het meest frequent in de ONDERLIP, vanwege de kwetsbaarheid voor bijten."},
    {q:"Het merendeel van de speekselstenen wordt aangetroffen in:",
     opts:["Gl. submandibularis","Gl. parotis","Gl. sublingualis","Kleine accessoire speekselklieren"],
     exp:"Sialolithiasis: ~80-90% in de gl. submandibularis vanwege de langere, gebogen ductus (Wharton) en de dikkere, mucineuze speeksel."},
    {q:"Welke speekselklier produceert een arm-mucinen (waterig seroze) secretie?",
     opts:["Gl. parotis","Gl. submandibularis","Gl. sublingualis","Kleine palatinale klieren"],
     exp:"De gl. parotis produceert uitsluitend sereus (waterig, eiwitrijk) speeksel met weinig mucine. De gl. submandibularis is gemengd sereus/mucineus."},
    {q:"De anaerobe glycolyse van Streptococcus mutans levert hoeveel ATP per glucosemolecuul op?",
     opts:["2 ATP","4 ATP","36 ATP","38 ATP"],
     exp:"Anaerobe glycolyse (Embden-Meyerhof-Parnas) levert netto 2 ATP per glucosemolecuul. Aerobe verbranding levert 36-38 ATP."},
    {q:"Waar wordt subgingivaal tandsteen voornamelijk gevormd?",
     opts:["Linguaal van de onderfront en vestibulair in de bovenmolaarstreek","Geen voorkeurslocatie; overal gelijk","Buccaal van de ondermolaren","Palatinaal van de bovenfrontelementen"],
     exp:"Subgingivaal tandsteen volgt dezelfde distributie als supragingivaal tandsteen: linguaal onderfront (uitmonding gl. submandibularis/sublingualis) en vestibulair bovenmolaren (uitmonding parotis)."}
  ]
},

// ══════════════════════════════════════════════════════════════════
// THK2 – 2018 DECEMBER
// ══════════════════════════════════════════════════════════════════

kinesio_cikmis_2018dec:{
  title:"Kinesiologie/TMD Cikmis – 2018 December",
  questions:[
    {q:"De discus articularis voorkomt slijtage van het gewrichtsoppervlak. Juist of onjuist?",
     opts:["Juist – de discus fungeert als schokdemper en verdeelaandrukkrachten","Onjuist – de discus veroorzaakt slijtage","Onjuist – de discus heeft geen functie bij slijtage","Juist – maar alleen bij normale discuspositie"],
     exp:"De discus articularis distribueert de gewrichtskrachten en fungeert als schokdemper, waardoor slijtage van het condylaire kraakbeen wordt voorkomen."},
    {q:"Het werkingsmechanisme van een opbeetplaat is gebaseerd op het verhinderen van verkeerde mondgewoonten. Juist of onjuist?",
     opts:["Onjuist – de opbeetplaat werkt ook via spierontspanning en redistributie van gewrichtsbelasting","Juist – het primaire mechanisme is gedragsmodificatie","Onjuist – een opbeetplaat werkt alleen door verhoging van de beethoogte","Juist – het is louter een herinneringsapparaat"],
     exp:"Opbeetplaten werken via meerdere mechanismen: spierontspanning, redistributie gewrichtskrachten, beperken bruxisme. Niet uitsluitend via gedragsmodificatie."},
    {q:"Een anteriore discusverplaatsing met reductie (ADD met reductie) komt vaker voor bij vrouwen dan bij mannen. Juist of onjuist?",
     opts:["Juist – TMD incl. ADD met reductie komt vaker voor bij vrouwen","Onjuist – gelijke verdeling over mannen en vrouwen","Onjuist – mannen hebben meer ADD","Juist – maar alleen na de menopauze"],
     exp:"TMD-aandoeningen, inclusief anteriore discusverplaatsing, komen significant vaker voor bij vrouwen (3:1 tot 5:1 vrouw:man ratio)."},
    {q:"Een snelle eerste screening op TMD bestaat uit inspectie van de dentitie en een bewegingsonderzoek. Juist of onjuist?",
     opts:["Juist – opening/sluiting/laterotrusive bewegingen + inspectie vormt de basisscreening","Onjuist – altijd MRI nodig voor TMD-screening","Onjuist – alleen anamnese is voldoende","Juist – maar ook palpatie van de kauwspieren hoort erbij"],
     exp:"De TMD-screening bestaat uit: anamnese, inspectie dentitie/occlusie, bewegingsonderzoek (opening, laterale bewegingen), palpatie spieren en gewrichten."},
    {q:"De hulpvraag van de TMD-patient is bepalend voor de behandelnoodzaak. Juist of onjuist?",
     opts:["Juist – de subjectieve klacht/behoefte van de patient bepaalt of behandeling geindceerd is","Onjuist – de klinische bevindingen bepalen de behandelnoodzaak","Onjuist – behandeling is altijd noodzakelijk bij TMD","Juist – maar alleen als er sprake is van pijn"],
     exp:"In de biopsychosociale benadering van TMD is de hulpvraag van de patient leidend. Asymptomatische bevindingen behoeven niet altijd behandeling."},
    {q:"Hoe meer voorafgaande behandelingen er zijn geweest, hoe beter de prognose van TMD-pijnbehandeling. Juist of onjuist?",
     opts:["Onjuist – meerdere eerdere behandelingen correleren met een slechtere prognose (chroniciteit)","Juist – ervaring maakt de patient beter behandelbaar","Onjuist – het aantal behandelingen heeft geen effect","Juist – eerdere behandelingservaring is nuttig"],
     exp:"Chronische TMD-pijn met multiple eerdere behandelingen wijst op chronicificatie en psychosociale factoren, wat de prognose verslechtert."},
    {q:"Bij het Dahl-effect zorgt extrusie van posterieure gebitselem voor 40% van de compensatoire uitgroei. Juist of onjuist?",
     opts:["Juist – ca. 40% extrusie posterior + ca. 60% intrusie anterieur","Onjuist – het is 100% intrusie","Onjuist – Dahl-effect heeft niets met extrusie te maken","Juist – maar alleen bij volwassen patienten"],
     exp:"Het Dahl-effect: anterieure restauratie -> anterieure intrusie (~60%) EN posterieure extrusie (~40%). Beide processen zorgen voor occlusale herinstelling."},
    {q:"Een patient kan haar mond niet dichtdoen met duidelijke deviatie van de onderkaak naar rechts. Meest waarschijnlijke diagnose?",
     opts:["Luxatie van het kaakgewricht links","Luxatie van het kaakgewricht rechts","Fractuur van de mandibula rechts","Spasme van de m. pterygoideus links"],
     exp:"Bij kaakgewrichtsluxatie is de condylus anterocranially verplaatst. Deviatie naar rechts = het linkse gewricht is geluxeerd (condylus links is te ver anterieur)."},
    {q:"Bij een anteriore discusverplaatsing in het linker kaakgewricht is er een knappend geluid links tijdens de mondopening. Juist of onjuist?",
     opts:["Juist – de knap treedt op als de condylus onder de discus glijdt bij opening (reductie)","Onjuist – de knap is rechts","Onjuist – knappende geluiden komen niet voor bij ADD met reductie","Juist – maar alleen bij sluiting"],
     exp:"ADD MET reductie: bij opening springt de condylus terug onder de discus -> opening-knap aan de IPSILATERALE zijde (links bij linkszijdige ADD)."},
    {q:"Bruxisme kan behandeld worden door counseling, opbeetplaat en medicatie. Juist of onjuist?",
     opts:["Juist – multimodale aanpak is de standaard","Onjuist – alleen opbeetplaat is effectief","Onjuist – bruxisme is niet te behandelen","Juist – maar medicatie is altijd de eerste keuze"],
     exp:"Bruxisme-behandeling is multimodaal: cognitieve gedragstherapie/counseling, opbeetplaat (nachtplaat), biofeedback, eventueel botulinum toxine of farmacotherapie."}
  ]
},

functie_cikmis_2018dec:{
  title:"Orale Functieleer/Prothetiek Cikmis – 2018 December",
  questions:[
    {q:"De plaatsing van implantaten bij een overkappingsprothese op twee implantaten verschilt tussen een steg en drukknoppen. Juist of onjuist?",
     opts:["Juist – bij een steg worden implantaten verder naar voren geplaatst dan bij drukknoppen","Onjuist – de plaatsing is identiek bij beide verbindingselementen","Onjuist – alleen de bovenkaak is anders","Juist – steg vereist meer afstand tussen implantaten"],
     exp:"Bij een steg worden de implantaten iets meer anterieur en distanter van elkaar geplaatst (interimplantatieafstand voor steg minimaal 22mm)."},
    {q:"Een overkappingsprothese op implantaten en een volledige prothese hebben hetzelfde kauwvermogen. Juist of onjuist?",
     opts:["Onjuist – overkappingsprothese heeft significant beter kauwvermogen","Juist – kauwvermogen is gelijk","Onjuist – een volledige prothese heeft beter kauwvermogen","Juist – maar alleen als de implantaten goed osseointegreert zijn"],
     exp:"Overkappingsprotheses op implantaten geven significant beter kauwvermogen, hogere kauwkracht en betere kwaliteit van leven dan conventionele volledige prothesen."},
    {q:"Bij het lingualized occlusie-concept occluderen de vestibulaire knobbels van de bovenmolaren met de fossa van de ondermolaren. Juist of onjuist?",
     opts:["Onjuist – bij lingualized occlusie occluderen de PALATINALE knobbels van boven met de centrale fossa van onder","Juist – de vestibulaire knobbels occluderen","Onjuist – er is geen knobbel-fossa contact","Juist – dit is het kenmerk van lingualized occlusie"],
     exp:"Lingualized occlusie: de prominente palatinale knobbels van de bovenmolaren occluderen in de centrale fossa van de ondermolaren. Vestibulaire knobbels zijn ingeslepen."},
    {q:"Bij het lingualized occlusie-concept is er frontcontact in maximale occlusie. Juist of onjuist?",
     opts:["Onjuist – bij lingualized occlusie is er GEEN frontcontact in MO","Juist – frontcontact is essentieel","Onjuist – alleen bij bilateraal gebalanceerde articulatie is er geen frontcontact","Juist – het front leidt de laterale bewegingen"],
     exp:"Lingualized occlusie voor prothesen: geen frontcontact in MO. Alleen occlusaal contact in het posterieure gedeelte (palatinale knobbels op fossa)."},
    {q:"Osseointegratieproces verloopt als: hemostase, ontstekingsfase, proliferatieve fase en remodelleringsfase. Of als hemostase, ontstekingsfase, remodelleringsfase en proliferatieve fase?",
     opts:["Hemostase, ontstekingsfase, proliferatieve fase en remodelleringsfase","Hemostase, ontstekingsfase, remodelleringsfase en proliferatieve fase","Proliferatieve fase, hemostase, ontstekingsfase, remodelleringsfase","Ontstekingsfase, hemostase, proliferatieve fase, remodelleringsfase"],
     exp:"De fasen van wondgenezing (en osseo-integratie) zijn: 1. Hemostase, 2. Ontsteking, 3. Proliferatie, 4. Remodellering."},
    {q:"De definitieve kenmerk voor peri-implantitis is:",
     opts:["Botafbraak rondom het implantaat","Pusvorming","Bloeding bij sonderen","Verdiepte pocket"],
     exp:"Peri-implantitis wordt gedefinieerd als botafbraak (rontgenologisch aantoonbaar) in combinatie met infectie. Pusvorming is een symptoom maar niet het definitieve kenmerk."},
    {q:"Het trigonium mandibulare is geen belangrijk steunpunt voor de gebitsprothese. Juist of onjuist?",
     opts:["Onjuist – het trigonium mandibulare IS een belangrijk steunpunt (retromolaarpad)","Juist – het trigonium heeft geen steunfunctie","Onjuist – het is alleen bij edentate kaken relevant","Juist – de alveolaire kam is het enige steunpunt"],
     exp:"Het retromolaarpad/trigonium mandibulare is een vezelachtig weefselgebied dat als steungebied dient voor de onderkaasprothese, met name bij sterk geresorbeerde kaak."},
    {q:"Waarom laten we de rand van een kroon approximaal liever niet in een bestaande composietvulling eindigen?",
     opts:["Vanwege het gevaar van randlekkage","Omdat je composiet niet onder een kroon mag laten zitten","Vanwege esthetische redenen","Omdat composiet niet hard genoeg is voor de kroonrand"],
     exp:"Composiet veroudert en krimpt met de tijd. Een kroonrand op composiet heeft een verhoogd risico op marginale lekkage, secundaire caries en loosvallen van de kroon."},
    {q:"Irritatiefibromen worden veroorzaakt door te lange protheseranden. Juist of onjuist?",
     opts:["Juist – chronische mechanische irritatie door overextended protheseranden leidt tot irritatiefibroom","Onjuist – irritatiefibromen zijn altijd goedaardig en spontaan","Onjuist – oorzaak is altijd een slechte mondhygiene","Juist – maar ook slechte mondhygiene speelt een rol"],
     exp:"Irritatiefibromen (epulis fissurata) ontstaan door langdurige chronische irritatie, meestal door te lange of slecht passende protheseranden."},
    {q:"Een tand die horizontaal is afgebroken tot het niveau van de gingiva kan voor ferrule orthodontisch worden geextrudeerd. Juist of onjuist?",
     opts:["Juist – orthodontische extrusie kan voldoende tandweefsel boven het botniveau brengen voor een ferrule-effect","Onjuist – een dergelijke tand moet altijd worden geextraheerd","Onjuist – orthodontische extrusie is te riskant","Juist – maar altijd gecombineerd met chirurgische kronenverlengig"],
     exp:"Orthodontische extrusie van een wortel met gecompliceerde kroonfractuur tot gingivaniveau kan voldoende klinische kroon creeren voor ferrule en kroonrestauratie."}
  ]
},

radio_cikmis_2018dec:{
  title:"Radiologie Cikmis – 2018 December",
  questions:[
    {q:"Bij adolescenten wordt met rontgenfoto ruim 50% meer dentinecaries gevonden dan klinisch. Juist of onjuist?",
     opts:["Juist – rontgenfoto detecteert proximale dentinecaries die klinisch niet zichtbaar is","Onjuist – rontgenfoto detecteert minder caries dan klinisch onderzoek","Onjuist – klinisch en rontgenologisch zijn gelijk","Juist – maar alleen voor glazuurcaries"],
     exp:"Meerdere studies bevestigen dat bitewing-opnamen significant meer dentinecaries detecteren, met name proximaal, dan klinisch onderzoek bij adolescenten."},
    {q:"Bij de bisectriceregel-techniek worden geen filmhouders toegepast. Juist of onjuist?",
     opts:["Juist – bij de bisectricetechniek wordt een halveeringsregel gebruikt zonder filmhouder","Onjuist – altijd filmhouders gebruiken","Onjuist – bisectricetechniek vereist een filmhouder","Juist – maar tegenwoordig worden filmhouders aanbevolen"],
     exp:"De bisectricetechniek maakt gebruik van de halveeringsregel (het bisectricum). Traditioneel zonder filmhouder, maar moderne varianten kunnen filmhouders gebruiken."},
    {q:"Welk materiaal is meer rontgenpak (radio-opaak): composiet of amalgaam?",
     opts:["Amalgaam is meer radio-opaak","Composiet is meer radio-opaak","Beide zijn even radio-opaak","Afhankelijk van de specifieke samenstelling"],
     exp:"Amalgaam (tin, zilver, kwik) is sterk radio-opaak. Moderne composieten bevatten zware metaalvullers en zijn ook radio-opaak, maar amalgaam is opaker."},
    {q:"De contrasten in een rontgenbeeld komen tot stand door een verschil in weglengte van de straling door het object. Juist of onjuist?",
     opts:["Juist – meer weefsel = meer absorptie = minder transmissie = witter rontgenbeeld","Onjuist – contrasten worden bepaald door straalenergie","Onjuist – het gaat om het atomair getal van het materiaal","Juist – maar ook het atomair getal speelt een rol"],
     exp:"Beide factoren spelen een rol: de fysieke dikte (weglengte) EN het atomair getal van het materiaal bepalen de absorptie en dus het contrast."},
    {q:"De geabsorbeerde dosis wordt uitgedrukt in:",
     opts:["Gray (Gy)","Sievert (Sv)","Becquerel (Bq)","Roentgen (R)"],
     exp:"Gray (Gy) is de eenheid voor geabsorbeerde dosis (J/kg). Sievert (Sv) is de equivalente/effectieve dosis (gewogen voor biologisch effect)."},
    {q:"Een te lichte rontgenfoto (onderbelicht) kan worden veroorzaakt door:",
     opts:["Te korte belichtingstijd","Te lange belichtingstijd","Te hoge buisspanning","Te lage kV"],
     exp:"Een te lichte (onderbelichte) foto: te weinig straling bereikt de detector. Oorzaken: te korte belichtingstijd, te laag mA, of te lage kV."},
    {q:"ALARA betekent:",
     opts:["As Low As Reasonably Achievable","As Low As Realistically Achievable","As Light As Reasonably Applicable","As Low As Regularly Assessed"],
     exp:"ALARA staat voor 'As Low As Reasonably Achievable'. Het principe van stralingsoptimalisatie in de radiologische diagnostiek."},
    {q:"Een onscherp begrensde radiolucency is een aanwijzing voor een maligne bottumor. Juist of onjuist?",
     opts:["Juist – infiltratief groeiend maligne weefsel geeft onscherpe grenzen","Onjuist – maligne tumoren zijn altijd scherp begrensd","Onjuist – grensbegrenzing zegt niets over maligniteit","Juist – maar ook infecties geven onscherpe grenzen"],
     exp:"Maligne bottumoren (metastasen, osteosarcoom) groeien infiltratief en geven onscherp begrensde radiolucencies. Benigne laesies zijn meestal scherp begrensd."},
    {q:"De eerste verschijning van een periapicale ontsteking is te zien als een radiolucente verbreding van de parodontaalspleet. Juist of onjuist?",
     opts:["Juist – verbreding van de APD-spleet is het vroegste rontgenologische teken van periapicale ontsteking","Onjuist – eerst een periapicale radiolucency","Onjuist – periapicale ontsteking is niet rontgenologisch zichtbaar","Juist – maar dit duurt weken tot maanden"],
     exp:"Het vroegste rontgenteken van periapicale parodontitis is verbreding/verdikking van de apicale periodontaalruimte. Pas later ontstaat een duidelijke radiolucency."},
    {q:"Voor parodontale diagnostiek worden bitewing-opnamen gebruikt. Juist of onjuist?",
     opts:["Juist – bitewing-opnamen tonen het alveolaire bot en de interproximale gebieden optimaal","Onjuist – voor paro worden alleen panoramische opnamen gebruikt","Onjuist – periapicale opnamen zijn het enige alternatief","Juist – maar ook periapicale opnamen zijn nodig"],
     exp:"Bitewing-opnamen zijn de meest geschikte opname voor parodontale diagnostiek: ze tonen alveolaire botniveaus en interdentale gebieden met minimale vertekening."}
  ]
},

basis_cikmis_2018dec:{
  title:"Basis Medisch Cikmis – 2018 December",
  questions:[
    {q:"Een patient die 8 maanden geleden een hartinfarct heeft gehad, wil nu behandeld worden. Wat is uw beleid voor lokale anesthesie?",
     opts:["Verdoving met lage adrenaline is toegestaan","Geen verdoving geven","Uitsluitend algehele narcose toepassen","Uitsluitend naar ziekenhuis verwijzen"],
     exp:"Na een hartinfarct (>6 maanden geleden, stabiel) is verdoving met lage dosis adrenaline (max 0,04 mg) toegestaan. In de eerste 6 maanden: terughoudend."},
    {q:"Een patient heeft een bloeddruk van 210/135 mmHg voor de behandeling. U mag gewoon verdoving geven. Juist of onjuist?",
     opts:["Onjuist – systolisch >180 of diastolisch >110 mmHg is een contra-indicatie voor electieve tandheelkundige behandeling","Juist – bloeddruk heeft geen invloed op verdoving","Onjuist – u mag verdoving geven zonder adrenaline","Juist – mits lage adrenaline gebruikt wordt"],
     exp:"Een bloeddruk van 210/135 mmHg is ernstige hypertensie (graad 3). Electieve behandeling uitstellen tot BP gecontroleerd is. Bloeddruk >180/110 = contra-indicatie."},
    {q:"Kenmerkend bij multiple sclerose (MS) is:",
     opts:["De klachten wisselen in ernst en plaats (relapsing-remitting patroon)","Mannen zijn vaker aangedaan dan vrouwen","Progressieve verergering zonder remissie","Altijd aanwezig vanaf de geboorte"],
     exp:"MS is een inflammatoire demyeliniserende aandoening. Kenmerkend: klachten die op- en afvlammen op wisselende plaatsen in het CZS (relapsing-remitting). Vaker bij vrouwen."},
    {q:"Spierarbeid verhoogt de insulinebehoefte. Juist of onjuist?",
     opts:["Onjuist – spierarbeid verlaagt de insulinebehoefte door verhoogde glucoseopname","Juist – inspanning verhoogt glucose en insuline","Juist – spieren verbruiken insuline direct","Onjuist – spierarbeid heeft geen effect op insuline"],
     exp:"Tijdens spierarbeid worden glucosetransporters (GLUT4) naar de spiercelmembraan getransporteerd, onafhankelijk van insuline. Insulinebehoefte daalt bij inspanning."},
    {q:"Een patient die 10 jaar geleden botkanker had en intraveneus bisfosfonaten kreeg, moet dit melden aan de tandarts vanwege:",
     opts:["Risico op osteonecrose van de kaak (BRONJ/MRONJ) na invasieve ingrepen","Risico op excessive bloeding","Contra-indicatie voor verdoving","Verhoogd infectierisico"],
     exp:"Intraveneuze bisfosfonaten (zolendroninezuur e.a.) accumuleren in kaakbot voor jaren. Na extractie/chirurgie: risico op medicatie-gerelateerde osteonecrose van de kaak (MRONJ)."},
    {q:"Patienten met ernstige decompensatio cordis kunnen niet lang platliggen. Juist of onjuist?",
     opts:["Juist – platliggen veroorzaakt orthopnoe door veneuze terugvloed naar de longen","Onjuist – platliggen is juist beter voor het hart","Onjuist – alleen bij rechtszijdig hartfalen","Juist – maar alleen bij volledig platliggen (niet bij 45 graden)"],
     exp:"Decompensatio cordis met longoedeem: bij platliggen neemt de veneuze terugvloed toe en verergert de dyspnoe (orthopnoe). Patienten slapen rechtop."},
    {q:"Een TIA wordt veroorzaakt door:",
     opts:["Een tijdelijke afsluiting van een hersenarterie","Ongecoordineerde elektrische activiteit in de hersenen","Een bloeding in de hersenen","Een arteriosclerotische plaque in de carotis"],
     exp:"TIA (Transient Ischaemic Attack) = voorbijgaande ischemie door tijdelijke afsluiting van een hersenarterie. Volledig herstel binnen 24 uur. Epilepsie = elektrische activiteit."},
    {q:"HIV kan zich in de mond manifesteren als ernstige parodontitis. Juist of onjuist?",
     opts:["Juist – HIV-geassocieerde parodontitis (linear gingival erythema, NUP) is een bekende manifestatie","Onjuist – HIV heeft geen orale manifestaties","Onjuist – HIV veroorzaakt alleen kandidose","Juist – maar alleen bij AIDS-stadium"],
     exp:"HIV-geassocieerde orale manifestaties: linear gingival erythema, NUP (Necrotizing Ulcerative Periodontitis), kandidose, hairy leukoplakia, Kaposi-sarcoom."},
    {q:"Penicillines en tetracyclines kunnen zonder probleem worden gecombineerd. Juist of onjuist?",
     opts:["Onjuist – tetracycline (bacteriostatisch) antagoniseert het effect van penicilline (bactericide)","Juist – ze werken op verschillende mechanismen","Onjuist – combinatie is gevaarlijk vanwege nierbelasting","Juist – synergistisch effect"],
     exp:"Penicilline is bactericide (werkt op delende bacterien). Tetracycline is bacteriostatisch (remt deling). Tetracycline antagoniseert het bactericide effect van penicilline."},
    {q:"Het gebruik van inhalatiesteroiden bij astmapatienten kan orale kandidose veroorzaken. Juist of onjuist?",
     opts:["Juist – inhalatiecorticosteroiden lokaal in de mond supprimeren de immuunrespons","Onjuist – inhalatiesteroiden zijn veilig voor de mond","Onjuist – alleen systemische steroiden veroorzaken kandidose","Juist – maar alleen bij hoge doseringen"],
     exp:"ICS (inhalatiesteroiden) als budesonide, fluticason: lokale immuunsuppressie in de orofarynx -> kolonisatie van Candida. Mondspoelingen na inhalatie reduceert het risico."},
    {q:"Zwangere vrouwen hebben vaak last van gingivitis. Juist of onjuist?",
     opts:["Juist – verhoogde geslachtshormonen versterken de gingivale ontstekingsreactie","Onjuist – zwangerschap heeft geen effect op de gingiva","Onjuist – gingivitis verbetert tijdens zwangerschap","Juist – maar alleen bij slechte mondhygiene"],
     exp:"Zwangerschapsgingivitis: oestrogeen en progesteron versterken de vasculaire permeabiliteit en inflammatoire respons van de gingiva op plaque."},
    {q:"De patient dient het gebruik van acetylsalicylzuur (aspirine) te staken voor een bloedige tandheelkundige ingreep. Juist of onjuist?",
     opts:["Onjuist – aspirine niet stoppen; lokale hemostase is afdoende bij tandheelkundige ingrepen","Juist – stoppen 7-10 dagen voor ingreep","Onjuist – aspirine moet verdubbeld worden","Juist – maar alleen bij doses boven 100 mg"],
     exp:"Cardioprotectief aspirine (80-100 mg) NIET stoppen: tromboserisico > bloedingsrisico. Lokale hemostase (tamponade, hechten) is afdoende bij tandheelkundige ingrepen."},
    {q:"Zwangere vrouwen mogen geen verdoving met felypressine ontvangen. Juist of onjuist?",
     opts:["Juist – felypressine (vasopressine-analoog) kan uteruscontracties veroorzaken","Onjuist – felypressine is veilig in de zwangerschap","Onjuist – adrenaline is de enige contra-indicatie","Juist – maar alleen in het eerste trimester"],
     exp:"Felypressine (Octapressin) is een vasopressine-analoog dat uteruscontracties kan induceren. Gecontra-indiceerd in de zwangerschap. Adrenaline (laag gedoseerd) is veilig."},
    {q:"Een granulomateuze ontsteking is een acute ontsteking. Juist of onjuist?",
     opts:["Onjuist – een granulomateuze ontsteking is een CHRONISCHE ontsteking","Juist – granulomen vormen zich acuut","Onjuist – granulomen zijn geen ontsteking","Juist – granulomen kunnen acuut en chronisch zijn"],
     exp:"Een granuloma = aggregaat van geactiveerde macrofagen (epitheloid cellen) + lymfocyten. Kenmerkend voor CHRONISCHE granulomateuze ontsteking (bv. Crohn, TB, sarcoidose)."}
  ]
},

statistiek_cikmis_2018dec:{
  title:"Statistiek Cikmis – 2018 December",
  questions:[
    {q:"Een onderzoeker wil vier groepen patienten vergelijken (dieet A, B, C, D) op gewichtsverandering in kg. Welke toets is het meest geschikt?",
     opts:["Variantie-analyse (ANOVA)","Chi-kwadraat toets","Independent samples t-toets","Pearson correlatie"],
     exp:"4 groepen, continue variabele (kg): ANOVA (eenweg variantie-analyse). Chi-kwadraat is voor categorische variabelen. T-toets is voor 2 groepen."},
    {q:"H0: mu1 < 50. Tweezijdige p-waarde = 0,11. Significantieniveau alpha = 5%. Mag de nulhypothese worden verworpen?",
     opts:["Nee – p=0,11 > alpha=0,05, nulhypothese wordt NIET verworpen","Ja – p < 0,10 dus de nulhypothese wordt verworpen","Ja – tweezijdige toets past altijd bij een eenzijdige hypothese","Nee – tweezijdige p moet verdubbeld worden"],
     exp:"Beslisregel: verwerp H0 als p < alpha. Hier p=0,11 > alpha=0,05, dus H0 wordt NIET verworpen."},
    {q:"De power van een studie hangt alleen maar af van de grootte van de steekproef. Juist of onjuist?",
     opts:["Onjuist – power hangt af van steekproefgrootte, effectgrootte, alpha-niveau en spreiding","Juist – grotere steekproef = altijd hogere power","Onjuist – power hangt alleen van alpha af","Juist – steekproefgrootte is de enige bepalende factor"],
     exp:"Power (1-beta) wordt bepaald door: n (steekproefgrootte), effectgrootte (delta), alpha-niveau en de spreiding (SD). Alle vier factoren spelen mee."},
    {q:"Voor de variabele 'bloedglucosespiegel in mmol/L' mag de range berekend worden. Juist of onjuist?",
     opts:["Juist – bloedglucose is een ratio-variabele, range mag worden berekend","Onjuist – bloedglucose is ordinaal","Onjuist – range is alleen voor nominale variabelen","Juist – maar alleen het gemiddelde is zinvol"],
     exp:"Bloedglucose (mmol/L) is een ratio-variabele (absoluut nulpunt). Voor ratio-variabelen mag alle statistische maten worden berekend, inclusief range."},
    {q:"Een onderzoeker vergelijkt 55-plussers versus <55 jaar op correct/incorrect tellen van gebitselementen. Welke toets past het best?",
     opts:["Chi-kwadraat toets (2 categorische variabelen)","Independent samples t-toets","ANOVA","Pearson correlatie"],
     exp:"Twee categorische variabelen (leeftijdsgroep en correct/incorrect) -> chi-kwadraat test. T-toets is voor een continue uitkomst."},
    {q:"Voor X=5,4,3,2,1 en Y=4,6,8,10,12 geldt: r (Pearson correlatie) = 0. Juist of onjuist?",
     opts:["Onjuist – er is een perfecte negatieve correlatie (r = -1)","Juist – er is geen correlatie","Onjuist – r = +1 (positieve correlatie)","Juist – r is altijd 0 bij kleine steekproeven"],
     exp:"Als X stijgt met 1, daalt Y met 2. Perfect lineair negatief verband. Pearson r = -1, niet 0."},
    {q:"Het meetniveau van een xerostomie-schaal van 1-5 (helemaal niet tot helemaal wel) is ratio. Juist of onjuist?",
     opts:["Onjuist – het meetniveau is ORDINAAL (geen gelijke intervals, geen absoluut nulpunt)","Juist – een schaal van 1-5 is altijd ratio","Onjuist – het is nominaal","Juist – Likert-schalen zijn altijd ratio"],
     exp:"Een Likert-achtige schaal (helemaal niet...helemaal wel) heeft ordinaal meetniveau: rangorde aanwezig, maar geen gelijke intervals en geen echt nulpunt."}
  ]
},

// ══════════════════════════════════════════════════════════════════
// THK1 – 2019 DECEMBER
// ══════════════════════════════════════════════════════════════════

paro_cikmis_2019dec:{
  title:"Parodontologie Cikmis – 2019 December",
  questions:[
    {q:"1-6 elementen met verdiepte pockets worden beschouwd als gegeneraliseerde parodontitis. Juist of onjuist?",
     opts:["Onjuist – gegeneraliseerde parodontitis vereist >30% aangedane elementen","Juist – elk aantal verdiepte pockets = gegeneraliseerd","Onjuist – 1-6 elementen is lokale parodontitis","Juist – maar alleen als pockets >6mm zijn"],
     exp:"Gegeneraliseerde parodontitis (2018 classificatie) = >30% van de elementen aangedaan. 1-6 elementen = gelokaliseerde parodontitis."},
    {q:"Horizontale mobiliteit van 2,5 mm hoort bij mobiliteitsgraad:",
     opts:["Graad 2 (meer dan 1mm maar minder dan 2mm)","Graad 3 (meer dan 2mm)","Graad 1 (tot 1mm)","Graad 0 (fysiologisch)"],
     exp:"Miller graad 2 = meer dan 1mm horizontale mobiliteit tot 2mm. Graad 3 = meer dan 2mm OF verticale mobiliteit. 2,5mm is dus GRAAD 3."},
    {q:"Antidepressiva veroorzaken veel speeksel (hypersalivatie). Juist of onjuist?",
     opts:["Onjuist – de meeste antidepressiva veroorzaken DROGE MOND (xerostomie) als bijwerking","Juist – antidepressiva stimuleren de speekselklieren","Onjuist – antidepressiva hebben geen effect op speeksel","Juist – alleen tricyclische antidepressiva"],
     exp:"Antidepressiva (TCA, SSRI) hebben anticholinerge bijwerkingen waaronder xerostomie (droge mond). Hypersalivatie is zeldzaam en niet kenmerkend."},
    {q:"Een grote pocketreductie met paro-chirurgie kan pas na 1 jaar opnieuw worden uitgevoerd. Juist of onjuist?",
     opts:["Juist – na paro-chirurgie dient minimaal 1 jaar afgewacht te worden voor re-evaluatie","Onjuist – na 3 maanden kan al opnieuw geopereerd worden","Onjuist – er is geen tijdsinterval vereist","Juist – maar alleen als de pocket volledig genezen is"],
     exp:"Na paro-chirurgie wordt minimaal 1 jaar afgewacht voor nieuwe chirurgie: weefselrijping, evaluatie van het resultaat en compliance-beoordeling."},
    {q:"Fluor wordt niet als antimicrobieel middel bij cariespreventie gebruikt omdat:",
     opts:["Bij preventieve concentraties is de antimicrobiele werking onvoldoende; hogere concentraties veroorzaken fluorose","Fluor heeft helemaal geen antimicrobiele werking","Fluor is te duur als antimicrobieel middel","Fluor doodt alleen Lactobacillus"],
     exp:"Fluoride heeft wel antimicrobiele eigenschappen, maar de concentraties die bij preventie worden gebruikt zijn onvoldoende antimicrobieel. Hogere concentraties veroorzaken fluorose."},
    {q:"Mucocele / slijmcyste wordt gevonden in de mondbodem. Juist of onjuist?",
     opts:["Onjuist – een ranula bevindt zich in de mondbodem; een mucocele is in de ONDERLIP","Juist – mucocele is kenmerkend voor de mondbodem","Juist – mucoceles komen op alle plaatsen voor","Onjuist – mucoceles komen niet in de mond voor"],
     exp:"Ranula = grote mucusretentiecyste in de mondbodem (sublingualis-klier). Mucocele = onderlip (kleinste accessoire speekselklieren door bijten). Andere benaming voor dezelfde pathologie."},
    {q:"Fossa canina is een beruchte plek voor parodontale ontsteking en afbraak. Juist of onjuist?",
     opts:["Juist – de dunne buccale botplaat ter hoogte van de hoektanden maakt dit gebied kwetsbaar","Onjuist – fossa canina is juist goed beschermd","Onjuist – parodontale afbraak treedt niet op in de fossa canina","Juist – maar alleen bij generaliseerde parodontitis"],
     exp:"De buccale botplaat ter hoogte van de cuspidaat (fossa canina) is extreem dun. Dit maakt het gebied kwetsbaar voor parodontale botafbraak en fenestration/dehiscentie."},
    {q:"Bij paro-behandeling en HbA1c bij diabetici: paro-behandeling kan HbA1c verlagen. Juist of onjuist?",
     opts:["Juist – meta-analyses tonen gemiddeld 0,3-0,4% HbA1c-daling na paro-behandeling","Onjuist – paro-behandeling heeft geen effect op HbA1c","Onjuist – alleen insuline beinvloedt HbA1c","Juist – maar alleen bij type 1 DM"],
     exp:"Meerdere meta-analyses (o.a. Engebretson & Kocher 2013, Sanz 2018) tonen een bescheiden maar significante HbA1c-daling na paro-behandeling bij diabetes."}
  ]
},

endo_cikmis_2019dec:{
  title:"Endodontologie Cikmis – 2019 December",
  questions:[
    {q:"De compatibiliteit van duaal-composietcement bij glasvezelstiften heeft voorkeur vanwege:",
     opts:["Compatibiliteit aanhechting aan glasvezels EN composietopbouw","Hoge flexibiliteit vergelijkbaar met dentine","Goedkope prijs","Gemakkelijke verwijdering bij mislukking"],
     exp:"Glasvezelstift + duaal-composietcement + composietopbouw: alle drie het zelfde hechtingssubstraat (composiet-matrix). Chemische en mechanische compatibiliteit."},
    {q:"80% van parodontitis apicalis veroorzaakt apicale resorptie. Juist of onjuist?",
     opts:["Onjuist – apicale resorptie treedt op bij slechts een minderheid van periapicale laesies","Juist – apicale resorptie is een kenmerk van PA","Juist – resorptie treedt altijd op bij chronische PA","Onjuist – resorptie treedt nooit op bij PA"],
     exp:"Apicale externe wortelresorptie kan optreden bij periapicale ontsteking, maar het is niet bij de meerderheid aanwezig. Apicale verbreding APD is het vroegste teken."},
    {q:"Welke is een warme guttapercha-vultechniek?",
     opts:["Guttapercha-injectietechniek (bijv. Obtura)","Laterale condensatie (koude techniek)","Enkelpuntmethode","Pasteuze injectie met AH Plus"],
     exp:"Warme technieken: warme verticale condensatie, Thermafil (carrier-based), guttapercha-injectie (Obtura, E&Q). Laterale condensatie is een KOUDE techniek."},
    {q:"MTA: gips (calciumsulfaat) versnelt de verhardingsreactie. Juist of onjuist?",
     opts:["Juist – calciumsulfaat wordt toegevoegd aan MTA om de verhardingstijd te verkorten","Onjuist – gips vertraagt de verhardingsreactie van MTA","Onjuist – gips heeft geen effect op MTA","Juist – maar te veel water maakt het zwak"],
     exp:"MTA = Portlandcement + bismutoxide. In Portlandcement wordt gips (calciumsulfaat) bewust toegevoegd om de verhardingstijd te VERTRAGEN (anders te snel). Bij MTA versnelt extra gips de reactie."},
    {q:"Bij een tijdelijke pijn na WKB met zwelling: schrijft u voor:",
     opts:["Antibiotica als er een abces/cellulitis aanwezig is, anders NSAIDs","Altijd antibiotica","Alleen paracetamol","Drainage uitvoeren zonder medicatie"],
     exp:"Na WKB met hevige pijn + zwelling (flare-up, phoenix-abces): draineren indien mogelijk. Antibiotica alleen bij uitbreiding infectie (celluitis, lymfadenopathie). NSAIDs voor pijn."},
    {q:"Bij een onvolledige kroonfractuur (cracked tooth) neemt de pijn toe bij:",
     opts:["Bij het openen van de kaak na kauwen (druk loslaten)","Bij het kauwen zelf","Bij koude prikkels","Bij warmte"],
     exp:"Cracked tooth: pijn bij het LOSLATEN van kauwdruk, niet bij het aandrukken. De fractuurdelen bewegen ten opzichte van elkaar bij drukverandering."},
    {q:"Een apicaal litteken op rontgenfoto is te herkennen als:",
     opts:["Een scherp begrensde radiolucency die na succesvolle WKB onveranderd blijft","Een radiolucency die na succesvolle WKB volledig verdwijnt","Een radiopaciteit rondom de apex","Een verbreding van de APD"],
     exp:"Apicaal litteken: cel-arm bindweefsel vervangt het ontstekingsweefsel. Op rontgen: scherp begrensde, stabiele radiolucency. Dit is GEEN teken van mislukking."},
    {q:"Als de papierpuntjes na irrigatie niet droog blijven, betekent dit:",
     opts:["De papierpunten zijn voorbij de apex geperst (over-instrumentatie)","Het kanaal is correct gereinigd","De sealant is compatibel","Meer irrigatie is nodig"],
     exp:"Als de papierpunten vochtig blijken op precies de kanaallengte, kan dit wijzen op over-instrumentatie (apex-perforatie). Alternatief: bloedspeeksel vanuit periapicale weefsels."}
  ]
},

cario_cikmis_2019dec:{
  title:"Cariologie Cikmis – 2019 December",
  questions:[
    {q:"Flowable (vloeibare) composieten hebben in vergelijking met anterieur-composieten:",
     opts:["Meer krimp bij de polymerisatie","Minder krimp bij de polymerisatie","Gelijke krimp","Geen krimp door hoge vulstofdichtheid"],
     exp:"Flowables bevatten meer harsmatrix en minder vulstof -> hogere polymerisatiekrimp dan conventionele/anterieure composieten."},
    {q:"Een kenmerk van een ACTIEVE carieslaesie in het glazuur is:",
     opts:["Een dof, ruw, wit oppervlak","Een zwart leerachtig oppervlak","Een glimmend, bruin oppervlak","Een gecaviteerde, natte laesie"],
     exp:"Actieve glazuurcaries: dof, ruw, wit (opake) oppervlak door actieve demineralisatie. Inactieve laesie: glad, glimmend, bruin (sclerotisch)."},
    {q:"Bij welke Ekstrand-score is het dentine NIET carieus?",
     opts:["Score 2 (schaduw in dentine, geen cavitatie)","Score 3 (microcavitatie)","Score 4 (cavitatie tot dentine)","Score 0 (gezond)"],
     exp:"Ekstrand score 2: schaduwvorming in dentine zichtbaar door het glazuur, MAAR geen cavitatie. Dentine is niet direct aangetast. Score 3: microcavitatie in glazuur."},
    {q:"Onder een restauratie zit zwart dentine. Dit wordt beschouwd als:",
     opts:["Inactieve caries (sclerotisch, geremineraliseerd dentine)","Actieve caries","Secundaire caries","Indicatie voor pulpakap"],
     exp:"Zwart hard dentine onder een restauratie = sclerotisch (inactief) dentine. Dit hoeft niet verwijderd te worden. Zacht bruin dentine = actief geinfecteerd."},
    {q:"Cariesdiagnostiek bij 47 distaal als de verstandskies afwezig is, wordt uitgevoerd via:",
     opts:["Directe inspectie of rontgenfoto","Indirect met spiegel","Sensibiliteitstests","Fluorescentiemeting"],
     exp:"Als de 48 ontbreekt, is de distale vlakte van 47 direct toegankelijk. Rontgenfoto is dan niet noodzakelijk voor diagnostiek; directe inspectie en sondering volstaan."},
    {q:"Een kaasmolaar (MIH) gaat altijd gepaard met glazuurbeschadiging bij alle elementen. Juist of onjuist?",
     opts:["Onjuist – MIH treft specifiek de eerste blijvende molaren en de centrale incisieven (niet alle elementen)","Juist – alle elementen zijn aangedaan","Onjuist – alleen de eerste molaren zijn aangedaan","Juist – maar alleen bij ernstige MIH"],
     exp:"MIH (Molaar-Incisief Hypomineralisatie): aangedane tanden zijn de eerste blijvende molaren (36, 46, 16, 26) en/of centrale incisieven (11, 21, 31, 41). Niet alle elementen."}
  ]
},

pedo_cikmis_2019dec:{
  title:"Kindertandheelkunde Cikmis – 2019 December",
  questions:[
    {q:"Ouders moeten kinderen helpen met tandenpoetsen tot de leeftijd van:",
     opts:["10 jaar (fijne motoriek volledig ontwikkeld)","6 jaar","8 jaar","12 jaar"],
     exp:"Fijne motoriek voor effectief zelfstandig tandenpoetsen is volledig ontwikkeld rond 10 jaar. Tot dan behoeven kinderen begeleiding van ouders."},
    {q:"Een kind van 6 jaar kan zijn tanden volledig zelfstandig goed poetsen. Juist of onjuist?",
     opts:["Onjuist – motorische vaardigheden voor effectief zelfstandig poetsen zijn niet volledig op 6 jaar","Juist – een 6-jarige kan prima zelfstandig poetsen","Onjuist – kinderen kunnen nooit zelfstandig poetsen","Juist – maar altijd onder supervisie"],
     exp:"Op 6-jarige leeftijd ontbreekt de benodigde fijne motoriek voor effectief poetsen. Ouders dienen tot ca. 10 jaar te helpen of te controleren."},
    {q:"Fluoride in tandpasta voor kinderen van 2-4 jaar:",
     opts:["500-750 ppm (peutertandpasta)","1000-1450 ppm (volwassen tandpasta)","250 ppm (babytandpasta)","Geen fluoride onder 4 jaar"],
     exp:"Ivoren Kruis / IADT: 0-1 jaar 500-750 ppm, 1-6 jaar 500-750 ppm (peutertandpasta). Volwassen tandpasta (>1000 ppm) wordt geadviseerd vanaf 6-7 jaar."},
    {q:"Kinderen tussen 2-5 jaar moeten twee keer per dag tandenpoetsen. Juist of onjuist?",
     opts:["Juist – 2x per dag poetsen is aanbevolen voor alle leeftijden","Onjuist – 1x per dag is voldoende voor kleuters","Onjuist – peutermelkgebit hoeft niet dagelijks gepoetst te worden","Juist – maar met een elektrische tandenborstel"],
     exp:"Ivoren Kruis: 2x per dag tandenpoetsen geldt voor alle leeftijden, inclusief kinderen van 2-5 jaar. Dit is de gouden standaard voor cariespreventie."},
    {q:"Waar staan de ouders bij het tandenpoetsen van hun kind?",
     opts:["Achter het kind (kind leunend in de armen/buik van de ouder)","Voor het kind","Naast het kind","Maakt niet uit"],
     exp:"De aanbevolen poetspositie: ouder staat ACHTER het kind, kind legt het hoofd achterover (kantel-methode). Dit geeft de ouder goed zicht en controle."},
    {q:"Een tweede melkmolaar die wordt getrokken omdat de premolaar aan het doorbreken is, telt mee in de DMFT-score. Juist of onjuist?",
     opts:["Onjuist – extractie van melkgebit om ruimte te geven telt NIET mee in de DMFT","Juist – elke extractie verhoogt de DMFT","Onjuist – alleen caries telt mee in de DMFT","Juist – de dMFT voor melkelementen"],
     exp:"DMFT geldt voor het blijvende gebit. Een melktandextractie voor de premolaar-doorbraak is geen caries-gerelateerde extractie en telt niet mee in de DMFT (permanente dentitie)."}
  ]
},

speeksel_cikmis_2019dec:{
  title:"Speeksel Cikmis – 2019 December",
  questions:[
    {q:"Zuigen op vitamine C tabletten kan tanderosie verminderen. Juist of onjuist?",
     opts:["Onjuist – vitamine C tabletten zijn zuur (pH < 4) en veroorzaken juist erosie","Juist – vitamine C heeft een beschermende werking","Onjuist – vitamine C heeft geen effect op tanderosie","Juist – als ze gekaauwd worden"],
     exp:"Vitamine C (ascorbinezuur) heeft een lage pH (~2,5-3). Langdurig zuigen op vitamine C tabletten geeft chemische erosie van het glazuur."},
    {q:"Pellikel kan werken als bescherming tegen tanderosie. Juist of onjuist?",
     opts:["Juist – het glazuurpellikel werkt als diffusiebarrierre en beschermt tegen zuurinwerking","Onjuist – pellikel versterkt erosie","Onjuist – pellikel heeft geen rol bij erosieprotectie","Juist – maar alleen bij basisch speeksel"],
     exp:"De eiwitpellikel (acquired pellicle) vormt een beschermende laag op het glazuur die de directe zuurinwerking vermindert en erosie vertraagt."},
    {q:"Net als bij gingivitispatienten zal bij parodontitispatienten de albumineconcentratie toenemen in mondvloeistof. Juist of onjuist?",
     opts:["Juist – bij parodontitis neemt vasculaire permeabiliteit toe, waardoor albumine uit gingivaal creviculair vocht lekt","Onjuist – albumine daalt bij parodontitis","Onjuist – albumine is niet aanwezig in mondvloeistof","Juist – maar alleen bij ernstige parodontitis"],
     exp:"Bij gingivitis en parodontitis neemt de gingivale bloedvaatpermeabiliteit toe. Serumeiwitten zoals albumine lekken via GCF in de mondvloeistof."},
    {q:"Paro verhoogt de proteolytische activiteit van speeksel. Juist of onjuist?",
     opts:["Juist – bacteriele proteases en inflammatoire mediatoren (MMP) zijn verhoogd bij parodontitis","Onjuist – paro heeft geen effect op speekselproteases","Onjuist – alleen caries beinvloedt speekselsamenstelling","Juist – maar alleen bij actieve paro"],
     exp:"Parodontitis: verhoogde bacteriele proteases + matrix metalloproteinasen (MMPs) uit gingivaal creviculair vocht verhogen de proteolytische activiteit in mondvloeistof."},
    {q:"Xerostomie wordt veroorzaakt door minder speekselproductie. Juist of onjuist?",
     opts:["Juist – xerostomie (droge mond) is geassocieerd met hyposalivatie","Onjuist – xerostomie kan ook optreden bij normale speekselproductie","Juist – maar alleen bij totale klierafwezigheid","Onjuist – xerostomie wordt veroorzaakt door te dik speeksel"],
     exp:"Xerostomie (subjectief droge mond) is meestal geassocieerd met verminderde speekselproductie (hyposalivatie), maar kan ook optreden bij veranderde speekselsamenstelling."}
  ]
},

// ══════════════════════════════════════════════════════════════════
// THK2 – 2019 SEPTEMBER (Functieherstel)
// ══════════════════════════════════════════════════════════════════

functie_cikmis_2019sep:{
  title:"Orale Functieleer/Prothetiek Cikmis – 2019 September",
  questions:[
    {q:"Irritatiefibromen ontstaan vaak door een slechte mondhygiene. Juist of onjuist?",
     opts:["Onjuist – irritatiefibromen ontstaan door mechanische irritatie (slechte protheserand), niet door slechte mondhygiene","Juist – plaque veroorzaakt irritatiefibromen","Onjuist – irritatiefibromen zijn altijd viraal","Juist – maar alleen bij immuno-gecompromitteerde patienten"],
     exp:"Irritatiefibromen (epulis fissuratum) worden veroorzaakt door chronische mechanische irritatie, met name door overextended of slecht passende protheseranden."},
    {q:"Bij de modiolus komen de m. masseter en de m. orbicularis oris samen. Juist of onjuist?",
     opts:["Onjuist – de modiolus is het punt waar de m. buccinator en m. orbicularis oris (en andere spieren) samenkomen, NIET de m. masseter","Juist – de masseter en orbicularis lopen samen","Onjuist – de modiolus bestaat niet","Juist – de masseter heeft een functie bij de modiolus"],
     exp:"De modiolus is een spiervezelknooppunt lateral van de mondhoek. Hier convergeren: m. buccinator, m. orbicularis oris, m. zygomaticus major, m. risorius e.a. Niet de masseter."},
    {q:"De m. buccinator is een van de spieren die de vorm van de protheserand bepalen. Juist of onjuist?",
     opts:["Juist – de m. buccinator bepaalt de buccale protheserand in de posterieure regio","Onjuist – de m. buccinator heeft geen invloed op de protheserand","Onjuist – alleen de m. orbicularis oris bepaalt de rand","Juist – maar alleen voor de bovenprothese"],
     exp:"De m. buccinator loopt horizontaal langs de wang en bepaalt mee de buccale randlengte van de prothese in de premolaar-/molaarstreek."},
    {q:"Bij tandeloze patienten met sterk geresorbeerde onderkaak liggen de aanhechtingsvezels van de m. mentalis op de processus alveolaris. Juist of onjuist?",
     opts:["Juist – bij extreme resorptie verschuift de insertie van de m. mentalis naar de top van de processus","Onjuist – de m. mentalis hecht altijd aan de mandibulaire basis","Onjuist – de m. mentalis hecht niet op het kaakbot","Juist – maar alleen bij volledig edentate kaken"],
     exp:"Bij sterk geresorbeerde onderkaak kan de aanhechting van de m. mentalis op of boven het niveau van de processus alveolaris liggen, wat retentieproblemen geeft."},
    {q:"De beethoogte is de afstand tussen de onder- en de bovenkaak wanneer de patient de S-klanken uitspreekt. Juist of onjuist?",
     opts:["Onjuist – de freeway space (rustpositie) wordt bepaald bij S-klanken; de beethoogte is de VDO bij maximale occlusie","Juist – S-klanken bepalen de beethoogte","Onjuist – beethoogte wordt bepaald door gelaatstekens","Juist – maar alleen bij edentate patienten"],
     exp:"Bij S-klank (fonetische methode) heeft de patient de minimale freespace. Dit bepaalt de RUSTPOSITIE, niet de occlusiehoogte. Beethoogte (VDO) = afstand bij tandencontact."},
    {q:"Het op de wang of op de tong bijten kan optreden als de molaren niet in de neutrale zone zijn opgesteld. Juist of onjuist?",
     opts:["Juist – als elementen te ver buccaal (wang bijten) of linguaal (tong bijten) staan t.o.v. de neutrale zone","Onjuist – wang- en tongbijten zijn geen gevolg van prothese-opbouw","Onjuist – de occlusie is de enige oorzaak","Juist – maar alleen bij lingualized occlusie"],
     exp:"De neutrale zone is het gebied waar wangen- en tongkrachten in evenwicht zijn. Elementen buiten de neutrale zone worden door wangen of tong gebeten."},
    {q:"Ten gevolge van botresorptie ontstaat bij edentate kaken een ongunstige intermaxillaire relatie. Juist of onjuist?",
     opts:["Juist – botresorptie verloopt differentieel (boven centripetaal, onder centrifugaal), wat een klasse-III-relatie geeft","Onjuist – botresorptie verbetert de intermaxillaire relatie","Onjuist – botresorptie heeft geen invloed op de kaakrelatie","Juist – maar alleen bij tandloze bovenkaken"],
     exp:"Botresorptie bij edentate kaken: bovenkaak resorbeer naar binnen en omhoog (centripetaal), onderkaak naar buiten en omlaag (centrifugaal). Resultaat: schijnbare klasse III."},
    {q:"De retentie van een gebitsprothese is het vermogen om horizontale krachten te weerstaan. Juist of onjuist?",
     opts:["Onjuist – retentie = weerstand tegen VERTIKALE (aantrekkende) krachten; stabiliteit = weerstand tegen horizontale krachten","Juist – retentie = horizontale weerstand","Onjuist – retentie is hetzelfde als stabiliteit","Juist – maar ook verticale krachten spelen een rol"],
     exp:"Retentie = weerstand van de prothese tegen vertikaal aftrekkende krachten. Stabiliteit = weerstand tegen horizontale/rotatoire krachten. Twee verschillende begrippen."},
    {q:"Als de linguale prothese rand ver voorbij de linea mylohyoidea ligt wordt de prothese door het bewegen van de tong van zijn plaats gelift. Juist of onjuist?",
     opts:["Juist – de m. mylohyoideus heft bij contractie en tilt de prothese als de rand te ver lingual/caudaal loopt","Onjuist – de linguale rand mag ruim voorbij de linea mylohyoidea","Onjuist – de linea mylohyoidea heeft geen invloed op de prothese","Juist – maar alleen bij slikbewegingen"],
     exp:"De m. mylohyoideus vormt de mondbodem. Als de prothese linguale rand te ver distaal van de linea mylohyoidea loopt, wordt de prothese bij tongbewegingen en slikken opgelicht."},
    {q:"Een long centric overbrugt de afstand tussen de centrale relatie en de maximale occlusie. Juist of onjuist?",
     opts:["Juist – long centric is een voorwaartse vrijheid van de mandibula vanuit CR naar MO","Onjuist – long centric en CR zijn identiek","Onjuist – long centric is de maximale laterale beweging","Juist – maar alleen bij volledig edentate patienten"],
     exp:"Long centric = een occlusaal vrijheidsgebied van CR (centrale relatie) naar MO (maximale intercuspidatie), zodat de patient kan sluiten in een licht anterieure positie."},
    {q:"Bilaterale gebalanceerde articulatie is noodzakelijk voor een stabiele prothese. Juist of onjuist?",
     opts:["Juist – bij excursieve bewegingen voorkomt bilaterale balans kanteling van de prothese","Onjuist – eenzijdig contact is voldoende","Onjuist – articulatie heeft geen invloed op prothetische stabiliteit","Juist – maar alleen bij lingualized occlusie"],
     exp:"Bij volledige prothesen stabiliseert bilaterale gebalanceerde articulatie (BGA) de prothese tijdens excursieve bewegingen door simultaan contact aan beide zijden."},
    {q:"Kaakbotresorptie is bij patienten met een conventionele gebitsprothese even groot als bij patienten met een overkappingsprothese. Juist of onjuist?",
     opts:["Onjuist – overkappingsprothese op implantaten of overkapte elementen geeft MINDER botresorptie","Juist – het type prothese maakt geen verschil","Onjuist – conventionele prothese geeft minder resorptie","Juist – botresorptie hangt alleen af van genetische factoren"],
     exp:"Overkappingsprothesen op implantaten of overkapte wortels stimuleren het kaakbot (proprioceptie/krachttransmissie), waardoor de botresorptie significant verminderd wordt."},
    {q:"Het initiële resorptieproces van het kaakbot is het grootst in de eerste drie maanden na de extracties. Juist of onjuist?",
     opts:["Juist – botresorptie is het snelst in de eerste 3 maanden na extractie","Onjuist – resorptie is de eerste 2 jaar gelijk","Onjuist – resorptie start pas na 6 maanden","Juist – maar daarna houdt resorptie volledig op"],
     exp:"De snelste kaakbotresorptie treedt op in de eerste 3 maanden na tandextractie. Daarna vertraagt het proces maar gaat gedurende het leven door."},
    {q:"De eerste controle na het plaatsen van een immediaat prothese vindt na een week plaats. Juist of onjuist?",
     opts:["Onjuist – de eerste controle vindt de volgende dag (24 uur) na plaatsing plaats","Juist – controle na 1 week is standaard","Onjuist – controle na 2 weken is standaard","Juist – afhankelijk van de patient"],
     exp:"Na plaatsing van een immediaat prothese: eerste controle binnen 24-48 uur na plaatsing om drukplekken te verwijderen en occlusie te controleren."},
    {q:"Decapitatie van het pijlerelement bij een overkappingsprothese geschiedt op gingivaniveau. Juist of onjuist?",
     opts:["Onjuist – decapitatie geschiedt iets BOVEN gingivaniveau (supragin) zodat een domkoepelvorming koepel ontstaat","Juist – op gingivaniveau","Onjuist – op botniveau","Juist – maar alleen als er caries is"],
     exp:"Bij overkappingsprothese: de kroon/wortel wordt gesnoeid tot net boven het gingivaniveau (supragin), zodat een gepolijste koepelvorm ontstaat die reinigbaar is."}
  ]
},

// ══════════════════════════════════════════════════════════════════
// BASIS MEDISCH – 2019 DECEMBER
// ══════════════════════════════════════════════════════════════════

basis_cikmis_2019dec:{
  title:"Basis Medisch Cikmis – 2019 December",
  questions:[
    {q:"Een gezond hart pompt in rust per minuut ongeveer:",
     opts:["5-6 liter bloed (cardiale output)","1-2 liter bloed","10-12 liter bloed","3-4 liter bloed"],
     exp:"Cardiale output = slagvolume x hartfrequentie. In rust: ca. 70 ml/slag x 70 /min = ~5 liter/min. Dit is de normale cardiac output."},
    {q:"Een patient met tuberculose: wanneer mag u beginnen met tandheelkundige behandeling?",
     opts:["Na 2-3 weken antibiotische behandeling van de TB","Onmiddellijk starten met behandeling","Na 6 weken behandeling","Nooit behandelen bij actieve TB"],
     exp:"TB: behandeling uitstellen tot 2-3 weken na start van effectieve antibiotica. Dan is de patiect minder besmettelijk en mag tandheelkundige behandeling plaatsvinden."},
    {q:"Endocarditis wordt voornamelijk veroorzaakt door gram-positieve streptokokken. Juist of onjuist?",
     opts:["Juist – viridans-streptokokken (S. sanguinis, S. mutans) zijn de meest voorkomende verwekkers","Onjuist – gramnegatieven zijn de voornaamste oorzaak","Onjuist – endocarditis is viraal","Juist – maar alleen bij tandheelkundige ingrepen"],
     exp:"Bacteriele endocarditis wordt voor ~50-65% veroorzaakt door orale viridans-streptokokken (gram-positief), met name na orofaciale ingrepen."},
    {q:"Oligodontie: 6 of meer ontbrekende elementen in het blijvende gebit. Juist of onjuist?",
     opts:["Juist – oligodontie = 6 of meer ontbrekende permanente elementen (derde molaren niet meegerekend)","Onjuist – oligodontie begint bij 3 ontbrekende elementen","Onjuist – oligodontie geldt voor het melkgebit","Juist – oligodontie geldt voor alle tanden"],
     exp:"Definitie: oligodontie = 6 of meer congenitaal ontbrekende permanente tanden (exclusief 3e molaren). Hypodontie = 1-5 ontbrekende tanden."},
    {q:"Betablokkers veroorzaken bronchoconstrictie. Juist of onjuist?",
     opts:["Juist – betablokkers blokkeren beta-2-receptoren in de bronchien waardoor bronchoconstrictie optreedt","Onjuist – betablokkers geven bronchodilatatie","Onjuist – betablokkers hebben geen effect op de bronchien","Juist – maar alleen bij niet-selectieve betablokkers"],
     exp:"Niet-selectieve betablokkers (propranolol) blokkeren beta-2 receptoren in de bronchien -> bronchoconstrictie. Gecontra-indiceerd bij astma/COPD."},
    {q:"MRSA-besmetting vindt vooral plaats door lichamelijk contact (handen) of door niezen/kleding. Juist of onjuist?",
     opts:["Juist – MRSA verspreidt zich primair via direct contact, met handen als voornaamste overdrachtsroute","Onjuist – MRSA verspreidt zich via de lucht","Onjuist – MRSA verspreidt zich via bloedcontact","Juist – maar ook via aerosolen in de tandartspraktijk"],
     exp:"MRSA wordt voornamelijk overgedragen via contact, met handen als meest belangrijke vector. Standaard contactpreventie (handschoenen, handhygiene) is de eerste maatregel."},
    {q:"Herpes labialis wordt veroorzaakt door het herpes simplex virus. Juist of onjuist?",
     opts:["Juist – herpes labialis wordt veroorzaakt door HSV-1 (Herpes Simplex Virus type 1)","Onjuist – herpes labialis is bacterieel","Onjuist – herpes labialis is veroorzaakt door HSV-2","Juist – zowel HSV-1 als EBV"],
     exp:"Koortslip (herpes labialis) = HSV-1 reactivatie. Primaire infectie in de kindertijd, latent in ganglion trigeminale. Reactivatie bij stress, koorts, UV-straling."},
    {q:"Groeihormoon en insuline werken elkaar tegen. Juist of onjuist?",
     opts:["Juist – groeihormoon is insuline-antagonistisch (anti-insuline werking)","Onjuist – groeihormoon potentieert insuline","Onjuist – er is geen interactie","Juist – maar alleen bij GH-overschot"],
     exp:"Groeihormoon heeft diabetogene effecten (verhoogt bloedglucose). Insuline verlaagt bloedglucose. Ze zijn antagonisten. Acromegalie -> insulineresistentie."},
    {q:"Zwangere vrouwen hebben een verhoogde kans op gingivitis. Juist of onjuist?",
     opts:["Juist – oestrogeen en progesteron verhogen de vasculaire permeabiliteit en gingivale ontstekingsreactie","Onjuist – zwangerschap beschermt de gingiva","Onjuist – gingivitis verlengt de zwangerschap","Juist – maar alleen in het derde trimester"],
     exp:"Zwangerschapsgingivitis treedt op door hormonale veranderingen (oestrogeen/progesteron) die de gingivale microvasculatuur beinvloeden en de immuunrespons moduleren."},
    {q:"Een patient met een allergie voor verdoving: wat doet u?",
     opts:["U vraagt hoe de reactie precies was en vraagt naar documentatie (allergologisch rapport)","U geeft geen verdoving en behandelt zonder","U gaat er vanuit dat het klopt en geeft geen verdoving","U verwijst direct naar het ziekenhuis"],
     exp:"Een gerapporteerde verdovingsallergie moet worden uitgevraagd: wat voor reactie, wanneer, door wie vastgesteld. Echte allergie voor amide-anesthetica is zeldzaam; meestal is het vasovagaal of een andere reactie."},
    {q:"De normale diastolische bloeddruk is 110 mmHg. Juist of onjuist?",
     opts:["Onjuist – normale diastolische bloeddruk is ca. 80 mmHg; 110 mmHg is hypertensie graad 1","Juist – 110 mmHg is normaal","Onjuist – normaal is 60 mmHg","Juist – afhankelijk van leeftijd"],
     exp:"Normale bloeddruk: <120/80 mmHg. Hypertensie: >140/90 mmHg. Diastolisch 110 mmHg = ernstige hypertensie (graad 2), niet normaal."},
    {q:"Zure materialen en zuurstof stimuleren speekselsecretie. Juist of onjuist?",
     opts:["Juist – zuurprikkels (smaakstimuli) activeren de parasympathicus en verhogen speekselsecretie","Onjuist – zuur remt speekselsecretie","Onjuist – speekselsecretie wordt alleen door mechanische prikkels gestimuleerd","Juist – maar alleen smaakprikkels tellen"],
     exp:"Zuursmaken zijn sterke stimuli voor speekselsecretie via de smaak-reflexboog (chorda tympani -> nucleus salivatorius). Vliegangst of stress (stress) stimuleert ook het autonoom zenuwstelsel."},
    {q:"Omeprazol is een protonpompremmer (PPI). Juist of onjuist?",
     opts:["Juist – omeprazol remt irreversibel de H+/K+-ATPase (protonpomp) in de maagwandcellen","Onjuist – omeprazol is een H2-receptor antagonist","Onjuist – omeprazol is een antacidum","Juist – en ook een H2-remmer"],
     exp:"Omeprazol (PPI) remt irreversibel de H+/K+-ATPase in de parieetale maagwandcellen, waardoor de zuurproductie sterk verminderd wordt."},
    {q:"Paracetamol heeft geen invloed op de bloedstolling. Juist of onjuist?",
     opts:["Juist – paracetamol heeft geen of minimaal effect op de bloedplaatjesaggregatie","Onjuist – paracetamol remt de bloedstolling net als aspirine","Onjuist – paracetamol verhoogt het bloedingsrisico","Juist – maar alleen bij lage doseringen"],
     exp:"Paracetamol heeft geen klinisch relevant effect op de bloedplaatjesaggregatie of stolling. NSAIDs (ibuprofen, aspirine) remmen wel de trombocytenfunctie."},
    {q:"Ibuprofen is een pijnstiller en een ontstekingsremmer. Juist of onjuist?",
     opts:["Juist – ibuprofen is een NSAID met analgetische, antipyretische EN anti-inflammatoire werking","Onjuist – ibuprofen is alleen een pijnstiller","Onjuist – ibuprofen remt geen ontsteking","Juist – maar alleen bij hoge doseringen"],
     exp:"Ibuprofen = NSAID. Werkingsmechanisme: remming van COX-1 en COX-2 -> verminderde prostaglandinesynthese -> minder pijn, koorts EN ontsteking."}
  ]
}

};
window.QUIZZES = Object.assign(window.QUIZZES || {}, sets);
})();
